### ISSUE TITLE
shallow fetch_pack 

### ISSUE THREAD

**Issue by 5263** [dulwich/dulwich#240]
Is there a way to use fetch_pack to perform a shallow clone? I don't need the contents to be extracted into an existing repo. I don't need the graft points setup.

**Comment by jelmer** [comment]
On Sun, Dec 14, 2014 at 11:35:45PM -0800, 5263 wrote:
> Is there a way to use fetch_pack to perform a shallow clone? I don't need the contents to be extracted into an existing repo. I don't need the graft points setup. 
With grafts, you might be do something like that. milki?

**Comment by jelmer** [comment]
@milki any thoughts?

**Comment by jelmer** [comment]
Fixed in master.
