### ISSUE TITLE
"git clean -fd" using Dulwich

### ISSUE THREAD

**Issue by chamilad** [dulwich/dulwich#398]
Hi,

I couldn't find any documentation on executing the above task using Dulwich. Although dulwich.index.build_index_from_tree() resets the working directory, it doesn't clean any untracked files or folders. Is there a way in Dulwich to do this?

**Comment by jelmer** [comment]
Hi,

On Mon, Dec 07, 2015 at 11:56:12PM -0800, Chamila wrote:
> I couldn't find any documentation on executing the above task using Dulwich. Although dulwich.index.build_index_from_tree() resets the working directory, it doesn't clean any untracked files or folders. Is there a way in Dulwich to do this? 
There is no existing function you can you, though it would not be too hard to implement by yourself.

Essentially, use os.walk() to iterate over the contents of the directory tree, then check for each file whether it is present in the index to see if it needs to be kept or can be deleted.

Jelmer

**Comment by jelmer** [comment]
On Tue, Dec 08, 2015 at 06:00:45PM +0000, Jelmer Vernooij wrote:
> Hi,
> 
> On Mon, Dec 07, 2015 at 11:56:12PM -0800, Chamila wrote:
> > I couldn't find any documentation on executing the above task using Dulwich. Although dulwich.index.build_index_from_tree() resets the working directory, it doesn't clean any untracked files or folders. Is there a way in Dulwich to do this? 
> There is no existing function you can you, though it would not be too hard to implement by yourself.
> 
> Essentially, use os.walk() to iterate over the contents of the directory tree, then check for each file whether it is present in the index to see if it needs to be kept or can be deleted.

That said, it would of course be nice to have this functionality in Dulwich -
probably somewhere in dulwich.porcelain.reset. If you do write something like
this, I'd be grateful for a patch. :-)

Cheers,

Jelmer

**Comment by chamilad** [comment]
Thanks Jelmer! I'll try to send a PR for this. Shall I keep this open until that?

**Comment by jelmer** [comment]
On Tue, Dec 08, 2015 at 06:42:52PM -0800, Chamila wrote:
> Thanks Jelmer! I'll try to send a PR for this. Shall I keep this open until that? 
Thanks! Yes, let's keep this open.

**Comment by laneb** [comment]
> Essentially, use os.walk() to iterate over the contents of the directory tree, then check for each file whether it is present in the index to see if it needs to be kept or can be deleted.

`git clean -fd` without `-x` leaves alone files that have been ignored. 

I'm interested in implementing this. Is there any process for becoming a contributor, or should I just submit a PR?

**Comment by jelmer** [comment]
Yes, you're welcome to just submit a pull request.
