### ISSUE TITLE
Allow clone without check out 

### ISSUE THREAD

**Issue by cool-RR** [dulwich/dulwich#503]
`git clone` has a flag `--no-checkout` which is useful to me. It'll be nice if Repo.clone will have a similar flag.

**Comment by cool-RR** [comment]
My mistake, I didn't look at the porcelain module. Thanks for supplying this feature!

**Comment by cool-RR** [comment]
Or actually, maybe it shouldn't only be in the porcelain module? Because I'm using Dulwich from my program, and I think that the porcelain module isn't appropriate. What do you think about including this feature in Repo.clone?

**Comment by jelmer** [comment]
Having a no_checkout flag to Repo.clone() seems reasonable to me.

**Comment by cool-RR** [comment]
What about checkout=True ? Double negatives are ugly.

**Comment by jelmer** [comment]
Yeah, that might be better. So long as it's consists between the different parts of Dulwich.
