### ISSUE TITLE
Package bin/dulwich on Windows

### ISSUE THREAD

**Issue by segevfiner** [dulwich/dulwich#540]
The current packaged scripts can't be used easily on Windows since they are installed as extension-less Python scripts under the Python scripts directory. The best way to handle this is using the `console_scripts` feature of setuptools (This does add a dependency on it though, but that is quite common nowadays):

```py
entry_points={
    "console_scripts": [
        "dulwich = dulwich.__main__:main",
        "dul-receive-pack = dulwich.scripts.dul_receive_pack:main",  # Or another location in the package
        "dul-upload-pack = dulwich.scripts.dul_upload_pack:main",
    ],
},
```

Moving "bin/dulwich.py" to "dulwich/\_\_main__.py" will also enable `python -m dulwich` to work.

You might also want to add some `if __name__ == "__main__"` to the scripts once they are packaged inside the package.

### References
* https://packaging.python.org/tutorials/distributing-packages/#scripts
* https://packaging.python.org/tutorials/distributing-packages/#console-scripts
* https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation

**Comment by jelmer** [comment]
bin/dulwich isn't really in a great shape yet. It started its life as a test tool; before moving this code into the package, #175 should probably be addressed.

**Comment by jelmer** [comment]
The guts of bin/dulwich have now moved to dulwich/cli.py. I've changed it so that we use entry_points when setuptools is available and a trivial script otherwise (for when we're installing without setuptools).
