### ISSUE TITLE
allow depending on "dulwich[pure]" to disable C extension build

### ISSUE THREAD

**Issue by jelmer** [dulwich/dulwich#593]
There isn't an easy way to do this at the moment; you can only do this
using e.g. requirements.txt.

For setup.py, ideally we'd want to support something like
"dulwich[pure]" in your setup.py's install_requires, but I haven't
worked out the right magic to make that work in dulwich' setup.py yet. See
https://setuptools.readthedocs.io/en/latest/setuptools.html#id14 for
background on extras.

**Comment by Lothiraldan** [comment]
I tried adding a pure extra dependency but I cannot find a way to know if the `pure` extra dependency has been choosen or not in the DulwichDistribution class. If we find a way, it should be easy to add it.

Maybe it would be easier to add an extra dependency to use the C code but it wouldn't be backward compatible.

**Comment by jelmer** [comment]
I'd like the default to having C extensions enabled. If we do it the other way around, most people are going to end up with the slower version of Dulwich.

**Comment by Lothiraldan** [comment]
What about having two package? `dulwich` and `dulwich-pure`?

**Comment by jelmer** [comment]
I guess that's an option, though I'd rather avoid it if possible. It's less discoverable and requires I keep another project up to date.

On 5 June 2018 17:56:07 BST, Boris Feld <notifications@github.com> wrote:
>What about having two package? `dulwich` and `dulwich-pure`?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dulwich/dulwich/issues/593#issuecomment-394783467

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Suor** [comment]
If all the wheels were there this won't be an issue I guess.

**Comment by jelmer** [comment]
> If all the wheels were there this won't be an issue I guess.
Yep, that's the plan.

**Comment by jelmer** [comment]
I'm going to close this since I don't think the current python distutils infrastructure allows doing this, and Dulwich now has wheels for Ubuntu published for Linux, Mac OS X and Windows: https://pypi.org/project/dulwich/#files
