### ISSUE TITLE
String/bytes type of argument to branch_create() is unclear

### ISSUE THREAD

**Issue by detly** [dulwich/dulwich#612]
In the function [`porcelain.branch_create()`](https://github.com/dulwich/dulwich/blob/master/dulwich/porcelain.py#L1018), there are arguments `name` and `objectish`. `name` has to be bytes (ie. an encoded string) because of:

```python
refname = b"refs/heads/" + name
```
`objectish` has to be a string because of:

```python3
ref_message = b"branch: Created from " + objectish.encode('utf-8')
```

This could be clearer in the docstring, I kept tripping over it because I was pulling the `objectish` argument from code like:

```python3
branches = {
    ref for ref in repo.get_refs()
    if ref.startswith(b'refs/remotes/origin/')
} - tags
```

My `objectish` arguments were each element of this set, so I had to do `dulwich.porcelain.branch_create(repo, local_branch, branch.decode('utf8'))`.

**Comment by jelmer** [comment]
At least for porcelain.branch_{create,delete} this should now be fixed. There is still more work to be done for other functions in ``dulwich.porcelain``.
