### ISSUE TITLE
Intermittent error during push:  'SendPackError' object has no attribute 'message'

### ISSUE THREAD

**Issue by MattSable** [dulwich/dulwich#613]
I've been seeing this issue intermittently on Windows, Python 3+.

```
porcelain.py", line 786, in push
b" failed -> " + e.message.encode(err_encoding) +
AttributeError: 'SendPackError' object has no attribute 'message'
```

I don't have repro steps yet, but it looks like SendPackError is part of Dulwich.

**Comment by MattSable** [comment]
Just took another look. I think this is specific to Python 3+.

**Comment by MattSable** [comment]
So from what I can tell this is specific to Python 3+. Exception doesn't have message anymore. I think this can be fixed by just changing `e.message.encode(err_encoding)` to `str(e).encode(err_encoding)`. My concern though is the Push method will correctly print this error now, but doesn't actually raise an exception, so there's no indication anything went wrong from the caller. Is there any reason:

```
        except (UpdateRefsError, SendPackError) as e:
            errstream.write(b"Push to " + remote_location_bytes +
                            b" failed -> " + e.message.encode(err_encoding) +
                            b"\n")
```

shouldn't become this?

```
        except (UpdateRefsError, SendPackError) as e:
            errstream.write(b"Push to " + remote_location_bytes +
                            b" failed -> " + str(e).encode(err_encoding) +
                            b"\n")
            raise
```

**Comment by jelmer** [comment]
Yeah, it would make sense to raise an exception here. I think we should probably raise something more generic though, perhaps a PorcelainError that wraps the other error? Patches welcome.

**Comment by jelmer** [comment]
For SendPackError we now raise a PorcelainError.

For update problems with individual refs, those are now written to stdout.
