### ISSUE TITLE
when installed from pip, suddenly there are tons of new dependencies

### ISSUE THREAD

**Issue by chdiza** [dulwich/dulwich#616]
I just did `pip install -U dulwich` to upgrade my `dulwich` after seeing that a new version is out.

To my surprise, this required a jillion other dependencies to be installed by `pip`.  For as long as I can remember, `dulwich` hasn't brought in *any* other eggs as dependencies.  I can see nothing about these new dependencies in the `NEWS` file.

Is this intentional, or just some kind of slip-up in packaging up for PyPi?  I sure hope it's just the latter.  

Just FYI, the new dependencies that `pip` installed are: 
```
Installing collected packages: idna, six, pycparser, cffi, enum34, asn1crypto, ipaddress, cryptography, pyOpenSSL, certifi, urllib3
```

**Comment by jelmer** [comment]
There's one dependency that was intentional, on urllib3. This mentioned in NEWS in passing, though perhaps we should have called it out as a new dependency more explicitly.

On Debian, urllib3 only has a hard dependency on six (which was why I considered it an acceptable extra dependency). I'm not sure why they are hard dependencies on pypi, but that is indeed a long list :(

Reverting to urllib2 would mean reintroducing a bug with chunked requests.

@dandersson

**Comment by jelmer** [comment]
I see several options:

* Live with this (not ideal, I'd prefer to keep Dulwich a low-dependency module)
* Fallback to urllib2 somehow if urllib3 is not available. This is likely to be a source of confusion and bugs
* Make HTTP support optional, i.e. requiring a dependency on dulwich[http] to pull in the necessary dependencies
* Reduce the number of dependencies of urllib3 somehow (unlikely to happen?)

**Comment by chdiza** [comment]
I just checked using `pip` and found that `urllib3` has zero deps (I'm on macOS), and also `six` has zero deps.

This makes me think that whoever wrapped up `dulwich` for pip has accidentally brought in all that other stuff.

**Comment by chdiza** [comment]
I can see from [here](https://github.com/dulwich/dulwich/commit/48e2ef8c2f2c65a33ad3276458791c19ef208c1a) that it is apparently on purpose that all those crypto dependencies are brought in :)

**Comment by jelmer** [comment]
AFAIK pip configuration comes straight from Dulwiches setup.py, and that just depends on urllib3[secure]

**Comment by samuelharmer** [comment]
"urllib3" has no reqs. "urllib3[secure]", which is what Dulwich requires
has at least some of those you listed. My guess is the rest are
sub-dependencies.

**Comment by chdiza** [comment]
The link I mentioned suggests that the crypto business should only be brought in if Python is less than 2.7.9.  Mine is 2.7.14.

**Comment by jelmer** [comment]
that link shows the actual code, which is not what pypi uses for dependency resolution - dependency resolution happens using package metadata that comes straight out of setup.py.

**Comment by samuelharmer** [comment]
https://github.com/shazow/urllib3/blob/d5c8c68a8df0cb864d44a5ad00cb8f2ffc60bab8/setup.py#L65-L71

**Comment by jelmer** [comment]
Hmm, perhaps an option would be to just hide the https support behind a flag.

**Comment by mikofski** [comment]
I've updated the [conda-forge dulwich feedstock](https://github.com/conda-forge/dulwich-feedstock) recipe with the `urllib3[secure]` dependencies. Built, tested and released. :tada:

**Comment by jelmer** [comment]
This should mostly be addressed in master now; all dependencies except for urllib & certifi are now optional. urllib3 will warn if the version of the ssl module installed in unsafe, and applications can still patch in the openssl code if needs be for Python <= 2.7.9. 

If the dependency on urllib3 is an issue, we could possibly hide that behind a "dulwich[http]" extra, but I haven't done that for now as it may break things for those who rely on HTTP support at the moment.
