### ISSUE TITLE
dulwich.porcelain.clone No such file or directory on AWS Lambda

### ISSUE THREAD

**Issue by j2ali** [dulwich/dulwich#626]
I am trying to execute

```
dulwich.porcelain.clone('git@bitbucket.org:%s/%s.git' % (BITBUCKET_USER,BITBUCKET_REPO_NAME), '/tmp/repo')
```

in AWS Lambda, however I get 

```
"errorType": "OSError",
  "errorMessage": "[Errno 2] No such file or directory"
```

This works for me locally. Anyone having the same problem?

**Comment by jelmer** [comment]
Can you paste the full traceback? Apparently the /tmp on AWS Lambda is special in some way, though I don't have any experience with it myself.

**Comment by jelmer** [comment]
Closing this since it's still waiting for a reply after two years.
