### ISSUE TITLE
error: option --pure not recognized

### ISSUE THREAD

**Issue by QGB** [dulwich/dulwich#629]
pip install dulwich --global-option="--pure"

G:\QGB\Anaconda2\lib\site-packages\pip\_internal\commands\install.py:199: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting dulwich
  Using cached https://files.pythonhosted.org/packages/7b/1e/3d6368a7924ef909886fbedfefba6811409e56637dad109da127e234b8b3/dulwich-0.19.2.tar.gz
Collecting urllib3>=1.21 (from dulwich)
  Using cached https://files.pythonhosted.org/packages/ee/11/7c59620aceedcc1ef65e156cc5ce5a24ef87be4107c2b74458464e437a5d/urllib3-1.22.tar.gz
Collecting certifi (from dulwich)
  Using cached https://files.pythonhosted.org/packages/4d/9c/46e950a6f4d6b4be571ddcae21e7bc846fcbb88f1de3eff0f6dd0a6be55d/certifi-2018.4.16.tar.gz
Skipping bdist_wheel for dulwich, due to binaries being disabled for it.
Skipping bdist_wheel for urllib3, due to binaries being disabled for it.
Skipping bdist_wheel for certifi, due to binaries being disabled for it.
Installing collected packages: urllib3, certifi, dulwich
  Running setup.py install for urllib3 ... error
    Complete output from command g:\qgb\anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\admini~1\\appdata\\local\\temp\\pip-install-wnqxnu\\urllib3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --pure install --record c:\users\admini~1\appdata\local\temp\pip-record-4bgks2\install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --pure not recognized

    ----------------------------------------
Command "g:\qgb\anaconda2\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\admini~1\\appdata\\local\\temp\\pip-install-wnqxnu\\urllib3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" --pure install --record c:\users\admini~1\appdata\local\temp\pip-record-4bgks2\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\admini~1\appdata\local\temp\pip-install-wnqxnu\urllib3\

**Comment by jelmer** [comment]
As far as I can tell, most packages that want to depend on "Pure" Dulwich want this to avoid having to install a C compiler. See #707 where we're working to provide wheels for the various platforms; this should address the same concern.

**Comment by dsabsay** [comment]
Hmm. I ran into the same issue. Why is this not handled by setuptools? I see that`setup.py` is declaring the dependencies on urllib3 and certifi via the `install_requires` argument to setup(). Why is this not getting honored?

**Comment by jelmer** [comment]
> Hmm. I ran into the same issue. Why is this not handled by setuptools? I see that`setup.py` is declaring the dependencies on urllib3 and certifi via the `install_requires` argument to setup(). Why is this not getting honored?

Can you expand on that? How are urllib3 and certifi related here?

**Comment by dsabsay** [comment]
> > Hmm. I ran into the same issue. Why is this not handled by setuptools? I see that`setup.py` is declaring the dependencies on urllib3 and certifi via the `install_requires` argument to setup(). Why is this not getting honored?
> 
> Can you expand on that? How are urllib3 and certifi related here?

In your earlier reply, you suggested to resolve the issue as follows:

```
pip install urllib3 certifi
pip install dulwich --global-option="--pure"
```

Generally speaking, a Python package declares its dependencies in the `setup.py` file. Then when installing, `pip` knows to install the dependencies first. My question here is why did that not happen in this case?

**Comment by jelmer** [comment]
That does happen in this case, but pip tries to pass the --pure flag to the setup.py commands for urllib3 and certifi - and their setup.py doesn't understand that flag.

**Comment by jelmer** [comment]
We're now publishing wheels for Mac OS X, Linux and Windows, which will hopefully remove the need for requiring pure builds.

I'm going to close this bug since I don't think there is much that I can do here from the Dulwich side; this would need support from pip.
