### ISSUE TITLE
How to reproduce 'git diff commitA commitB -- file' with Dulwich

### ISSUE THREAD

**Issue by WladdGorshenin** [dulwich/dulwich#630]
I'm glad that Dulwich project exists and is evolving, I really like idea to have python API to Git. 

But because of lack of documentation I can't get how to reproduce what 'git diff commitA commitB -- file' command does.

Appreciate any help.

**Comment by jelmer** [comment]
Help on the documentation side of things would be great. 

Per file diffs:

    from dulwich.object_store import tree_lookup_path
    from dulwich.repo import Repo
    r = Repo('.')
    mode1, sha1 = tree_lookup_path(r.__getitem__, r[c1].tree, path)
    mode2, sha2 = tree_lookup_path(r.__getitem__, r[c2].tree, path)
    import difflib
    difflib.unified_diff(r[sha1].data.splitlines(), r[sha2].data.splitlines())

**Comment by WladdGorshenin** [comment]
Hey @jelmer thank you for the reply. It works for me! But I had to make some changes in dulwich/object.py file to properly handle byte arrays and operations on them with Python 3. I thought Dulwich is "Python3-friendly", am I wrong?

**Comment by jelmer** [comment]
Yes, Dulwich is Python3-compatible. Since Git is encoding-agnostic, most arguments in Dulwich need to be bytestrings.

E.g. you need to pass in ``path`` as a bytestring.

**Comment by WladdGorshenin** [comment]
Hi @jelmer, sorry I was wrong - path as a bytestring works perfect.

**Comment by jelmer** [comment]
Thanks for confirming :)
