### ISSUE TITLE
How to keep a repo in memory?

### ISSUE THREAD

**Issue by WladdGorshenin** [dulwich/dulwich#632]
I use Dulwich to calculate statistics about a Git repo for my research project. Therefore I need to do a lot of calculations and re-calculations on all object. What is the best way to keep a whole repo in memory in order to speed up the process?

**Comment by jelmer** [comment]
You can create a MemoryRepo, then fetch into that. See examples/memoryrepo.py for an example.

On 11 June 2018 09:35:57 CEST, WladdGorshenin <notifications@github.com> wrote:
>I use Dulwich to calculate statistics about a Git repo for my research
>project. Therefore I need to do a lot of calculations and
>re-calculations on all object. What is the best way to keep a whole
>repo in memory in order to speed up the process?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dulwich/dulwich/issues/632

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by WladdGorshenin** [comment]
Hi @jelmer , thank you for the lighting fast reply. You confirmed my idea. Currently I'm running an experiment with MemoryRepo. Hopefully it would reduce a processing time from 6 hours with disk repo.

**Comment by jelmer** [comment]
Great :-) Closing this issue; please reopen if you have more questions or ask on stackoverflow (tag: "dulwich").

**Comment by WladdGorshenin** [comment]
Hi @jelmer , as you suggested I asked my new question on StackOverflow (https://stackoverflow.com/q/50912696/9668773), but it seems to be not that responsive with Dulwich-related questions. Could you please help me with "git ls-files" equivalent?

**Comment by jelmer** [comment]
On Tue, Jun 19, 2018 at 05:15:47AM -0700, WladdGorshenin wrote:
> Hi @jelmer , as you suggested I asked my new question on StackOverflow (https://stackoverflow.com/q/50912696/9668773), but it seems to be not that responsive with Dulwich-related questions. Could you please help me with "git ls-files" equivalent?
Sorry about that. I've just replied on the stackoverflow question.

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by WladdGorshenin** [comment]
Hi @jelmer , could you please check my new question on Stackoverflow again.
