### ISSUE TITLE
Git diff header difference

### ISSUE THREAD

**Issue by Lothiraldan** [dulwich/dulwich#642]
Hello,

I'm trying to generate a diff of staged and unstaged files between the working copy and the working copy parent. I reused some low-levels functions from `dulwich.index` and `dulwich.patch` modules when I could.

I think I've found an issue with `dulwich.patch.gen_diff_header`. I tried applying the generated diff with `git apply` but got only error.

Here is the generated diff using upstream `gen_diff_header`:

```diff
diff --git a/stage_add b/stage_add
new mode 100644
index 0000000..e69de29 100644
diff --git a/stage_delete b/stage_delete
deleted mode 100644
index e69de29..0000000
diff --git a/stage_modify b/stage_modify
index e69de29..61b9ad0 100644
--- a/stage_modify
+++ b/stage_modify
@@ -0,0 +1 @@
+Modify
\ No newline at end of file
```
I ended up modifying `gen_diff_header` to makes `git apply` happy. The resulting diff that applies is:

```diff
diff --git a/stage_add b/stage_add
new file mode 100644
index 0000000..e69de29
diff --git a/stage_delete b/stage_delete
deleted file mode 100644
index e69de29..0000000
diff --git a/stage_modify b/stage_modify
index e69de29..61b9ad0 100644
--- a/stage_modify
+++ b/stage_modify
@@ -0,0 +1 @@
+Modify
\ No newline at end of file
```

The git version I'm using to apply the diff is 2.17.1.

Here is for reference my adjusted code:

```python

def gen_diff_header(paths, modes, shas):
    """Write a blob diff header.

    :param paths: Tuple with old and new path
    :param modes: Tuple with old and new modes
    :param shas: Tuple with old and new shas
    """
    (old_path, new_path) = paths
    (old_mode, new_mode) = modes
    (old_sha, new_sha) = shas
    shortid = dulwich.patch.shortid
    yield b"diff --git " + old_path + b" " + new_path + b"\n"

    if old_mode != new_mode:
        if new_mode is not None:
            if old_mode is not None:
                yield ("old file mode %o\n" % old_mode).encode("ascii")

            yield ("new file mode %o\n" % new_mode).encode("ascii")

        else:
            yield ("deleted file mode %o\n" % old_mode).encode("ascii")

    yield b"index " + shortid(old_sha) + b".." + shortid(new_sha)

    if new_mode is not None and old_mode is not None:
        yield (" %o" % new_mode).encode("ascii")

    yield b"\n"
```
I can make a pull-request with the new code but I wanted to opened an issue first to first have your opinion on the differences, I'm pretty sure I'm lacking some context that could impact the code.

**Comment by jelmer** [comment]
the aim of Dulwich is to behave similarly to C Git, so it would be great if you could propose a change that made it behave like C git in this case. Ideally with a test case, so this doesn't regress and so that we can keep refining the behaviour to be more alike :)

**Comment by Lothiraldan** [comment]
This was fixed by https://github.com/dulwich/dulwich/pull/696, closing
