### ISSUE TITLE
porcelain.clone() hangs if code that runs after requests user input

### ISSUE THREAD

**Issue by themanifold** [dulwich/dulwich#649]
I'm using click 6.7, and dulwich 0.19.5 to produce a minimal working bug example:

```
from dulwich import porcelain
import click
import tempfile
import shutil
import sys

class Config(object):
    def __init__(self) -> None:
        pass

pass_config = click.make_pass_decorator(Config)

@click.group()
@click.pass_context
def cli(ctx):
    ctx.obj = Config()

@cli.command()
@click.option("--foo")
@pass_config
def testclone(config, foo):
    click.prompt("something")

    try:
        shutil.rmtree("/tmp/foo")
    except:
        pass
    porcelain.clone("some_git_repo", "/tmp/foo")
        
    print("123")
    # sys.stderr.flush()
    click.prompt("bar")

if __name__ == "__main__":
    cli()
```
You'll find that if `sys.stderr.flush()` is uncommented, the code will hang at `Checking out ...`. Looking at the code, I can see that the `dulwich.porcelain.clone()` function writes to the `sys.stderr` bytestream but doesn't flush:
```
...
        if checkout and not bare and head is not None:
            errstream.write(b'Checking out ' + head.id + b'\n')
            r.reset_index(head.tree)
...
```
You can also fix this problem by putting an `errstream.flush()` immediately after the `errstream.write()`

I realise that this might be the fault of other modules no flushing stderr when they come and ask for user input on stdin, but it's probably best to code defensively? I've tested and reproduced this problem with cookiecutter's interactive option too.

**Comment by jelmer** [comment]
I can't reproduce this. I also don't understand why not flushing would result in a hang.

**Comment by themanifold** [comment]
OK, this is strange. I'm just reporting what I've observed and how I got around the problem. Here is more information about the system I'm using. Is there anything else you need?

```
pip freeze:
arrow==0.12.1astroid==2.0.4
atomicwrites==1.1.5attrs==18.1.0
backcall==0.1.0binaryornot==0.4.4
certifi==2018.4.16
chardet==3.0.4
chevron==0.12.2
click==6.7
cookiecutter==1.6.0
decorator==4.3.0
docker==3.4.0
docker-pycreds==0.3.0
dulwich==0.19.5
future==0.16.0idna==2.7
ipython==6.5.0
ipython-genutils==0.2.0isort==4.3.4
jedi==0.12.1
Jinja2==2.10jinja2-time==0.2.0
lazy-object-proxy==1.3.1
MarkupSafe==1.0
more-itertools==4.3.0mypy==0.620
parso==0.3.1
pexpect==4.6.0pickleshare==0.7.4
pluggy==0.7.1
poyo==0.4.1prompt-toolkit==1.0.15
ptyprocess==0.6.0
py==1.5.4Pygments==2.2.0
pylint==2.1.1
pytest==3.7.1python-dateutil==2.7.3
PyYAML==3.13
requests==2.19.1
simplegeneric==0.8.1
six==1.11.0
texttable==1.4.0
traitlets==4.3.2
typed-ast==1.1.0
urllib3==1.23
wcwidth==0.1.7
websocket-client==0.48.0
whichcraft==0.4.1
wrapt==1.10.11
```

```Python version: 3.6.6
lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        17.1.11
Codename:       Hakoila
```

**Comment by themanifold** [comment]
If you wait a bit, I'll try and create a dockerfile to reproduce the bug.

**Comment by themanifold** [comment]
OK, I don't have the time right now to fully flesh it out, but the Dockerfile should probably look like this:

```
FROM python:slim

ADD . /tmp/
WORKDIR /tmp
RUN pip install -r /tmp/requirements.txt -q
```
And the directory where you run `docker build . -t bug` from should probably contain the python script I had before along with a setup.py and requirements.txt:

```
from setuptools import setup

setup(
    install_requires=[
        'click',
        'dulwich',
    ],
)
```
```
# requirements.txt
#
# installs dependencies from ./setup.py, and the package itself,
# in editable mode
-e .
click >=6.7
dulwich >=0.19.5 --global-option=--pure
```
When you've built the image, you can `docker run -it bug bash` and then just `python hang.py`

**Comment by jelmer** [comment]
I think click would be a better target for this bug report - it's what breaks here, and I don't see what Dulwich would be doing wrong.

Can you reproduce this if you don't use Dulwich but simply add a call to err.write() instead of clone, or if you replace the call to click.prompt() with input("foo") ?

**Comment by themanifold** [comment]
So the answer to this is, yes, I can reproduce it by replacing `click.prompt()` with `input('foo')` - namely that I then need to press ENTER to cause the script to finish.

Just FYI, I've also used cookiecutter's interactive prompt to produce the same effect.

Would there be anything wrong in putting the flush inside the dulwich logic? I know you can't reproduce this error, but we might as well flush our streams when we exit the function.

**Comment by jelmer** [comment]
On Mon, Aug 20, 2018 at 04:13:54AM -0700, themanifold wrote:
> So the answer to this is, yes, I can reproduce it by replacing `click.prompt()` with `input('foo')` - namely that I then need to press ENTER to cause the script to finish.
input('foo') (like prompt) is supposed to wait for user input followed
by enter, so this sounds like it is working correctly.

Can you reproduce it if you replace the call to dulwich.clone() with a simple
call to sys.stderr.buffer.write(b'blah') ?

> Would there be anything wrong in putting the flush inside the dulwich logic? I know you can't reproduce this error, but we might as well flush our streams when we exit the function.
It's not Dulwich' responsibility - if the caller wants to flush stderr
for some reason, that's up to them. If click needs to have a stderr
flushed before it can do what it needs to do, then it should be
flushing.

On the practical side, we'd have to add it in lots of places in the
codebase. Many of these calls reduce the usefulness of buffering and
eventually make things slower (i.e. the exact reason that
sys.stderr.write doesn't call sys.stderr.flush itself after every
write).

Jelmer

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by themanifold** [comment]
So I can reproduce it with the replacement as you say - which points to the other modules I've used (click, cookiecutter). I'm just puzzled now about why you can't reproduce it.

**Comment by jelmer** [comment]
For me it just waits for input; once I've given that, it continues as normal.

**Comment by jelmer** [comment]
I'll close the Dulwich side of this, since it's not a Dulwich bug.
