### ISSUE TITLE
Dulwich throws AttributeException when used in pythonw

### ISSUE THREAD

**Issue by TheLastProject** [dulwich/dulwich#652]
I got the following report from an user: https://github.com/Pext/Pext/issues/125

On Pext's side, installing a module calls the install_module function. The only moment in that function when 1 downward arrow with an exception is printed is here:

https://github.com/Pext/Pext/blob/095f5a5a9121141ccd16704ee486e3c943315d3f/pext/__main__.py#L2835-L2839

Clearly, the issue lies in dulwich's porcelain.clone().

Looking further into that, dulwich does a .write call here:
https://github.com/dulwich/dulwich/blob/e924e8bdfb71a7ecb6f88f4e6627cb7d2e344e1a/dulwich/porcelain.py#L349

Looking at
https://github.com/dulwich/dulwich/blob/e924e8bdfb71a7ecb6f88f4e6627cb7d2e344e1a/dulwich/porcelain.py#L289-L291

errstream defaults to default_bytes_err_stream, which is defined as follows:

https://github.com/dulwich/dulwich/blob/e924e8bdfb71a7ecb6f88f4e6627cb7d2e344e1a/dulwich/porcelain.py#L142-L143

Looking at the Python documentation, it is incorrect to assume sys.stdout and sys.stderr are not None on Windows (see https://docs.python.org/3/library/sys.html#sys.stderr):
>Under some conditions stdin, stdout and stderr as well as the original values __stdin__, __stdout__ and __stderr__ can be None. It is usually the case for Windows GUI apps that aren’t connected to a console and Python apps started with pythonw.

I can probably fix this myself, but I'd need to know how you'd prefer this fixed. We could do either of the following:
1. Add a small fallback class with a .write function that does nothing (seems cleanest to me, but risks having to make a very complex class at some point)
2. A try/except AttributeError block around every .write call on errstream or outstream
3. A None-check before any write call.

Which would you prefer? Or do you perhaps have a better idea altogether?

**Comment by jelmer** [comment]
I think we should go with the first option; creating such a class should be fairly straightforward if you derive that class from io.RawIOBase.

The alternatives require changing every call site, which will be tricky to get right.
