### ISSUE TITLE
porcelain.clone doesn't honor credentials in url, mangles kwargs

### ISSUE THREAD

**Issue by blalor** [dulwich/dulwich#654]
`porcelain.clone` doesn't parse the `username:password` in the `source` param:

```
>>> r = porcelain.clone("https://hashityhashhash:x-oauth-basic@github.com/example/repo.git", target="/tmp/repo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "…/dulwich/porcelain.py", line 331, in clone
    **kwargs)
  File "…/dulwich/porcelain.py", line 1084, in fetch
    fetch_result = client.fetch(path, r, progress=errstream.write)
  File "…/dulwich/client.py", line 364, in fetch
    progress)
  File "…/dulwich/client.py", line 1544, in fetch_pack
    b"git-upload-pack", url)
  File "…/dulwich/client.py", line 1433, in _discover_references
    resp, read = self._http_request(url, headers, allow_compression=True)
  File "…/dulwich/client.py", line 1409, in _http_request
    (resp.status, url))
dulwich.errors.GitProtocolError: unexpected http resp 401 for https://github.com/example/repo.git/info/refs?service=git-upload-pack
```

It also doesn't use the `username` and `password` keyword arguments correctly:
```
>>> porcelain.clone("https://github.com/example/repo.git", target="/tmp/repo2", username="hashityhashhash", password="x-oauth-basic")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "…/dulwich/porcelain.py", line 331, in clone
    **kwargs)
  File "…/dulwich/porcelain.py", line 1083, in fetch
    remote_location, config=r.get_config_stack(), **kwargs)
  File "…/dulwich/client.py", line 1636, in get_transport_and_path
    return get_transport_and_path_from_url(location, **kwargs)
  File "…/dulwich/client.py", line 1597, in get_transport_and_path_from_url
    parsed, config=config, **kwargs), parsed.path
  File "…/dulwich/client.py", line 1363, in from_parsedurl
    password=password, username=username, **kwargs)
TypeError: type object got multiple values for keyword argument 'username'
```

Maybe-related: #249, #404, #445, #428

**Comment by QGB** [comment]
```
---------------------------------------------------------------------------
GitProtocolError                          Traceback (most recent call last)
<ipython-input-173-d779ef53d06e> in <module>
----> 1 git.up(urlp)

D:\test\git.py in up(url, path, commit_msg, name, email)
     54                                   , merge_heads=None
     55                                           )
---> 56         return bhash,dulwich.porcelain.push(repo.path, url , 'master',)
     57         # porcelain.push(repo.repo.path, result.url, branch_name, errstream=outstream)

C:\qgb\Python37-32\lib\site-packages\dulwich\porcelain.py in push(repo, remote_location, refspecs, outstream, errstream, **kwargs)
    914                 path, update_refs,
    915                 generate_pack_data=r.object_store.generate_pack_data,
--> 916                 progress=errstream.write)
    917             errstream.write(
    918                 b"Push to " + remote_location_bytes + b" successful.\n")

C:\qgb\Python37-32\lib\site-packages\dulwich\client.py in send_pack(self, path, update_refs, generate_pack_data, progress)
   1682         url = self._get_url(path)
   1683         old_refs, server_capabilities, url = self._discover_references(
-> 1684             b"git-receive-pack", url)
   1685         negotiated_capabilities = self._negotiate_receive_pack_capabilities(
   1686                 server_capabilities)

C:\qgb\Python37-32\lib\site-packages\dulwich\client.py in _discover_references(self, service, base_url)
   1613             tail += "?service=%s" % service.decode('ascii')
   1614         url = urlparse.urljoin(base_url, tail)
-> 1615         resp, read = self._http_request(url, headers, allow_compression=True)
   1616
   1617         if resp.redirect_location:

C:\qgb\Python37-32\lib\site-packages\dulwich\client.py in _http_request(self, url, headers, data, allow_compression)
   1591         elif resp.status != 200:
   1592             raise GitProtocolError("unexpected http resp %d for %s" %
-> 1593                                    (resp.status, url))
   1594
   1595         # TODO: Optimization available by adding `preload_content=False` to the
```

GitProtocolError: unexpected http resp 401 for https://qgb

**Comment by jelmer** [comment]
On Wed, Jan 29, 2020 at 07:28:17PM -0800, Too large to fit in the margin wrote:
> ```
> ---------------------------------------------------------------------------
> GitProtocolError                          Traceback (most recent call last)
> <ipython-input-173-d779ef53d06e> in <module>
> ----> 1 git.up(urlp)
> 
> D:\test\git.py in up(url, path, commit_msg, name, email)
>      54                                   , merge_heads=None
>      55                                           )
> ---> 56         return bhash,dulwich.porcelain.push(repo.path, url , 'master',)
>      57         # porcelain.push(repo.repo.path, result.url, branch_name, errstream=outstream)
> 
> C:\qgb\Python37-32\lib\site-packages\dulwich\porcelain.py in push(repo, remote_location, refspecs, outstream, errstream, **kwargs)
>     914                 path, update_refs,
>     915                 generate_pack_data=r.object_store.generate_pack_data,
> --> 916                 progress=errstream.write)
>     917             errstream.write(
>     918                 b"Push to " + remote_location_bytes + b" successful.\n")
> 
> C:\qgb\Python37-32\lib\site-packages\dulwich\client.py in send_pack(self, path, update_refs, generate_pack_data, progress)
>    1682         url = self._get_url(path)
>    1683         old_refs, server_capabilities, url = self._discover_references(
> -> 1684             b"git-receive-pack", url)
>    1685         negotiated_capabilities = self._negotiate_receive_pack_capabilities(
>    1686                 server_capabilities)
> 
> C:\qgb\Python37-32\lib\site-packages\dulwich\client.py in _discover_references(self, service, base_url)
>    1613             tail += "?service=%s" % service.decode('ascii')
>    1614         url = urlparse.urljoin(base_url, tail)
> -> 1615         resp, read = self._http_request(url, headers, allow_compression=True)
>    1616
>    1617         if resp.redirect_location:
> 
> C:\qgb\Python37-32\lib\site-packages\dulwich\client.py in _http_request(self, url, headers, data, allow_compression)
>    1591         elif resp.status != 200:
>    1592             raise GitProtocolError("unexpected http resp %d for %s" %
> -> 1593                                    (resp.status, url))
>    1594
>    1595         # TODO: Optimization available by adding `preload_content=False` to the
> ```
> 
> GitProtocolError: unexpected http resp 401 for https://qgb
Can you provide some context here? Are you providing valid credentials
in the URL and the server still gives you a 401?

Jelmer

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc
