### ISSUE TITLE
The PyPI metadata for dulwich are broken since version 0.19.4

### ISSUE THREAD

**Issue by zvezdan** [dulwich/dulwich#658]
The metadata for dulwich on PyPI changed between versions 0.19.3 and 0.19.4.
The important package data used by some automated build tooling is invalid now (for the latest 0.19.6).
See:
* https://pypi.org/project/dulwich/0.19.3/ and observe the classifiers, license, ... correctly present
* https://pypi.org/project/dulwich/0.19.4/ and observe classifiers, license, ... missing. It is available in the description at the bottom of the page, all packed into a single line, but it breaks the metadata for dulwich package.

See also: https://pypi.org/pypi/dulwich/json
```
..., "home_page":"","keywords":"","license":"","maintainer":"","maintainer_email":"", ...
```
Since this page is used by some automated tooling, and these fields are empty, it breaks the handling of the package.

**Comment by jelmer** [comment]
This is probably due to the migration to setup.cfg. It's not clear to me at a quick glance how that broke things, so perhaps we should revert that for the moment.

**Comment by zvezdan** [comment]
Thanks a lot for fixing this. It'll help when the next release comes out on PyPI.
