### ISSUE TITLE
Capability to specify a timeout for SSH related socket connections or transactions

### ISSUE THREAD

**Issue by ozn0417** [dulwich/dulwich#662]
Need to be able to set timeouts for ssh connections when doing clone, pull, fetch (from dulwich.porcelain).
If there are any long transactions, the function calls like above mentioned, would essentailly timeout when using among any webservice.

**Comment by jelmer** [comment]
On Sat, Sep 29, 2018 at 08:06:34PM -0700, ozn0417 wrote:
> Need to be able to set timeouts for ssh connections when doing clone, pull, fetch (from dulwich.porcelain).
> If there are any long transactions, the function calls like above mentioned, would essentailly timeout when using among any webservice.
Please clarify. What are you running that doesn't work?

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc
