### ISSUE TITLE
porcelain.pull() overwrites local changes (including commits)

### ISSUE THREAD

**Issue by peircej** [dulwich/dulwich#666]
For example:
1. fetch a repo:
```
import dulwich.porcelain as git
r = git.clone("git://github.com/jelmer/dulwich", "dulwich-clone")
```
2. delete a file locally
3. (optional) staged the deleted file and commit the change
4. pull again from remote:
```
git.pull(r, "git://github.com/jelmer/dulwich")
```

When step 4 is executed steps 2 and 3 are undone! That means we have to always commit, push then pull, whereas traditional git behaviour is to pull first then push.

Is there a workaround using the plumbing approach?

**Comment by peircej** [comment]
Ah, I just found this from 5 years ago
https://stackoverflow.com/questions/15966707/git-dulwichhow-to-merge-or-rebase
so now I'm assuming that merging still isn't supported. But then having a function `pull()` seems a strange thing if it doesn't merge, so I'm a little puzzled

**Comment by jelmer** [comment]
On Mon, Oct 29, 2018 at 03:39:45PM +0000, Jon Peirce wrote:
> For example:
> 1. fetch a repo:
> ```
> import dulwich.porcelain as git
> r = git.clone("git://github.com/jelmer/dulwich", "dulwich-clone")
> ```
> 2. delete a file locally
> 3. (optional) staged the deleted file and commit the change
> 4. pull again from remote:
> ```
> git.pull(r, "git://github.com/jelmer/dulwich")
> ```
> 
> When step 4 is executed steps 2 and 3 are undone! That means we have to always commit, push then pull, whereas traditional git behaviour is to pull first then push.
> 
> Is there a workaround using the plumbing approach?
Not directly using plumbing; it looks like porcelain.pull doesn't
currently check for diverged branches.

Pull also only support no-ff pulling at the moment. 

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by peircej** [comment]
Dang, OK, I guess I need to continue requiring a native git installation for now :-(

> Not directly using plumbing; it looks like porcelain.pull doesn't currently check for diverged branches.
>
> Pull also only support no-ff pulling at the moment.

In this instance the pull is simply a parent of the current HEAD. I expected nothing to happen, but the file was deleted and the history overwritten.
