### ISSUE TITLE
Push to AWS Code Commit fails with "dulwich.errors.HangupException: The remote server unexpectedly closed the connection."

### ISSUE THREAD

**Issue by WhileLoop** [dulwich/dulwich#671]
Based on examples/memoryrepo.py, the following code fails when using AWS Code Commit.

```import stat
from dulwich import porcelain
from dulwich.objects import Blob
from dulwich.repo import MemoryRepo

target = "https://git-codecommit.us-west-2.amazonaws.com/v1/repos/MyRepo"
username = "iam-user"
password = "iam-password"

local_repo = MemoryRepo()
local_repo.refs.set_symbolic_ref(b'HEAD', b'refs/heads/master')
print(local_repo.refs.as_dict())

porcelain.fetch(local_repo, target, username = username, password = password)
local_repo['refs/heads/master'] = local_repo['refs/remotes/origin/master']

last_tree = local_repo[local_repo['HEAD'].tree]
new_blob = Blob.from_string(b'Some contents')
local_repo.object_store.add_object(new_blob)
last_tree.add(b'test', stat.S_IFREG, new_blob.id)
local_repo.object_store.add_object(last_tree)

local_repo.do_commit(
    message=b'Add a file called \'test\'',
    ref=b'refs/heads/master',
    tree=last_tree.id)

porcelain.push(local_repo, target, 'master', username = username, password = password)
```

Output:
```
$ python2 memoryrepo_codecommit.py 
{}
Counting objects: 12, done.
Traceback (most recent call last):
  File "memoryrepo_codecommit.py", line 28, in <module>
    porcelain.push(local_repo, target, 'master', username = username, password = password)
  File "/usr/local/lib/python2.7/site-packages/dulwich/porcelain.py", line 816, in push
    progress=errstream.write)
  File "/usr/local/lib/python2.7/site-packages/dulwich/client.py", line 1625, in send_pack
    resp_proto, negotiated_capabilities, progress)
  File "/usr/local/lib/python2.7/site-packages/dulwich/client.py", line 551, in _handle_receive_pack_tail
    self._read_side_band64k_data(proto, channel_callbacks)
  File "/usr/local/lib/python2.7/site-packages/dulwich/client.py", line 476, in _read_side_band64k_data
    for pkt in proto.read_pkt_seq():
  File "/usr/local/lib/python2.7/site-packages/dulwich/protocol.py", line 254, in read_pkt_seq
    pkt = self.read_pkt_line()
  File "/usr/local/lib/python2.7/site-packages/dulwich/protocol.py", line 202, in read_pkt_line
    raise HangupException()
dulwich.errors.HangupException: The remote server unexpectedly closed the connection.
```

**Comment by jelmer** [comment]
On Wed, Nov 21, 2018 at 12:45:41PM -0800, Argishti Rostamian wrote:
> Based on examples/memoryrepo.py, the following code fails when using AWS Code Commit.
> 
> ```import stat
> from dulwich import porcelain
> from dulwich.objects import Blob
> from dulwich.repo import MemoryRepo
> 
> target = "https://git-codecommit.us-west-2.amazonaws.com/v1/repos/MyRepo"
> username = "iam-user"
> password = "iam-password"
> 
> local_repo = MemoryRepo()
> local_repo.refs.set_symbolic_ref(b'HEAD', b'refs/heads/master')
> print(local_repo.refs.as_dict())
> 
> porcelain.fetch(local_repo, target, username = username, password = password)
> local_repo['refs/heads/master'] = local_repo['refs/remotes/origin/master']
> 
> last_tree = local_repo[local_repo['HEAD'].tree]
> new_blob = Blob.from_string(b'Some contents')
> local_repo.object_store.add_object(new_blob)
> last_tree.add(b'test', stat.S_IFREG, new_blob.id)
> local_repo.object_store.add_object(last_tree)
> 
> local_repo.do_commit(
>     message=b'Add a file called \'test\'',
>     ref=b'refs/heads/master',
>     tree=last_tree.id)
> 
> porcelain.push(local_repo, target, 'master', username = username, password = password)
> ```
> 
> Output:
> ```
> $ python2 memoryrepo_codecommit.py 
> {}
> Counting objects: 12, done.
> Traceback (most recent call last):
>   File "memoryrepo_codecommit.py", line 28, in <module>
>     porcelain.push(local_repo, target, 'master', username = username, password = password)
>   File "/usr/local/lib/python2.7/site-packages/dulwich/porcelain.py", line 816, in push
>     progress=errstream.write)
>   File "/usr/local/lib/python2.7/site-packages/dulwich/client.py", line 1625, in send_pack
>     resp_proto, negotiated_capabilities, progress)
>   File "/usr/local/lib/python2.7/site-packages/dulwich/client.py", line 551, in _handle_receive_pack_tail
>     self._read_side_band64k_data(proto, channel_callbacks)
>   File "/usr/local/lib/python2.7/site-packages/dulwich/client.py", line 476, in _read_side_band64k_data
>     for pkt in proto.read_pkt_seq():
>   File "/usr/local/lib/python2.7/site-packages/dulwich/protocol.py", line 254, in read_pkt_seq
>     pkt = self.read_pkt_line()
>   File "/usr/local/lib/python2.7/site-packages/dulwich/protocol.py", line 202, in read_pkt_line
>     raise HangupException()
> dulwich.errors.HangupException: The remote server unexpectedly closed the connection.
> ```

Does shelling out to C Git instead of Dulwich for the push operation
work?

Jelmer

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by WhileLoop** [comment]
Modified code for local repo:

```
import stat
from dulwich import porcelain
from dulwich.objects import Blob
from dulwich.repo import Repo

target = "https://git-codecommit.us-west-2.amazonaws.com/v1/repos/MyRepo"
username = "iam-user"
password = "iam-password"

local_repo = porcelain.clone(target, 'MyRepo', username = username, password = password)

local_repo.refs.set_symbolic_ref(b'HEAD', b'refs/heads/master')
print(local_repo.refs.as_dict())

porcelain.fetch(local_repo, target, username = username, password = password)
local_repo['refs/heads/master'] = local_repo['refs/remotes/origin/master']

last_tree = local_repo[local_repo['HEAD'].tree]
new_blob = Blob.from_string(b'Some contents')
local_repo.object_store.add_object(new_blob)
last_tree.add(b'test', stat.S_IFREG, new_blob.id)
local_repo.object_store.add_object(last_tree)

local_repo.do_commit(
    message=b'Add a file called \'test\'',
    ref=b'refs/heads/master',
    tree=last_tree.id)

porcelain.push(local_repo, target, 'master', username = username, password = password)
```

Fails with same error:

```
$ python2 localrepo_codecommit.py 
Counting objects: 15, done.
Checking out 93d6f8d873c81f4c6f3ce2ef18358ffa1a4c0cf7
{'HEAD': '93d6f8d873c81f4c6f3ce2ef18358ffa1a4c0cf7', 'refs/remotes/origin/master': '93d6f8d873c81f4c6f3ce2ef18358ffa1a4c0cf7', 'refs/heads/master': '93d6f8d873c81f4c6f3ce2ef18358ffa1a4c0cf7'}
Traceback (most recent call last):
  File "localrepo_codecommit.py", line 29, in <module>
    porcelain.push(local_repo, target, 'master', username = username, password = password)
  File "/usr/local/lib/python2.7/site-packages/dulwich/porcelain.py", line 816, in push
    progress=errstream.write)
  File "/usr/local/lib/python2.7/site-packages/dulwich/client.py", line 1625, in send_pack
    resp_proto, negotiated_capabilities, progress)
  File "/usr/local/lib/python2.7/site-packages/dulwich/client.py", line 551, in _handle_receive_pack_tail
    self._read_side_band64k_data(proto, channel_callbacks)
  File "/usr/local/lib/python2.7/site-packages/dulwich/client.py", line 476, in _read_side_band64k_data
    for pkt in proto.read_pkt_seq():
  File "/usr/local/lib/python2.7/site-packages/dulwich/protocol.py", line 254, in read_pkt_seq
    pkt = self.read_pkt_line()
  File "/usr/local/lib/python2.7/site-packages/dulwich/protocol.py", line 202, in read_pkt_line
    raise HangupException()
dulwich.errors.HangupException: The remote server unexpectedly closed the connection.
```

Afterwards a cd into the local repo and successfully git push.

```
$ cd MyRepo/
$ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   test

$ git push
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 292 bytes | 292.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
To https://git-codecommit.us-west-2.amazonaws.com/v1/repos/MyRepo
   93d6f8d..ec9af06  master -> master
```

**Comment by jelmer** [comment]
Also, what version of Dulwich/Python are you using? There was a recent fix for preserving username/password in 0.19.9 (though since you're actually getting a "Counting objects: " line, I doubt that's the issue).

**Comment by WhileLoop** [comment]
Python 2.7.14 (default, Apr 25 2018, 15:22:05) 
dulwich==0.19.9

**Comment by jelmer** [comment]
Hmm, that doesn't provide a lot of output unfortunately :(

Can you try again with this patch applied::

```
=== modified file 'dulwich/client.py'
--- old/dulwich/client.py	2018-11-14 02:05:25 +0000
+++ new/dulwich/client.py	2018-11-28 02:42:28 +0000
@@ -1593,6 +1593,7 @@
         url = self._get_url(path)
         old_refs, server_capabilities, url = self._discover_references(
             b"git-receive-pack", url)
+        print(server_capabilities)
         negotiated_capabilities = self._negotiate_receive_pack_capabilities(
                 server_capabilities)
         negotiated_capabilities.add(capability_agent())


```

It appears to mostly get through but gets interrupted somewhere in the tail of the request.

**Comment by WhileLoop** [comment]
```$ python2 memoryrepo_codecommit.py 
Counting objects: 18, done.
{'refs/remotes/origin/master': 'ec9af06f4443ba6260c56ee8e8116d8a2cb92673'}
set(['side-band-64k', 'report-status', 'delete-refs', 'thin-pack'])
Traceback (most recent call last):
  File "memoryrepo_codecommit.py", line 28, in <module>
    porcelain.push(local_repo, target, 'master', username = username, password = password)
  File "/usr/local/lib/python2.7/site-packages/dulwich/porcelain.py", line 816, in push
    progress=errstream.write)
  File "/usr/local/lib/python2.7/site-packages/dulwich/client.py", line 1626, in send_pack
    resp_proto, negotiated_capabilities, progress)
  File "/usr/local/lib/python2.7/site-packages/dulwich/client.py", line 551, in _handle_receive_pack_tail
    self._read_side_band64k_data(proto, channel_callbacks)
  File "/usr/local/lib/python2.7/site-packages/dulwich/client.py", line 476, in _read_side_band64k_data
    for pkt in proto.read_pkt_seq():
  File "/usr/local/lib/python2.7/site-packages/dulwich/protocol.py", line 254, in read_pkt_seq
    pkt = self.read_pkt_line()
  File "/usr/local/lib/python2.7/site-packages/dulwich/protocol.py", line 202, in read_pkt_line
    raise HangupException()
dulwich.errors.HangupException: The remote server unexpectedly closed the connection.
```

**Comment by jelmer** [comment]
Thanks. I was hoping this would reveal something about what server it's running (newer git versions add an 'agent=git/1.2.3' capability), but at the very least this should help us figure out what code path it's taking through Dulwich

**Comment by jelmer** [comment]
Do you happen to know what server the server side is running?

**Comment by jelmer** [comment]
Ah :-/ The main option remaining then is to step through the code and see where it gets stuck. Do you happen to have a test server that I can reproduce this with?

**Comment by jelmer** [comment]
Unfortunately this needs somebody with access to AWS Code Commit to do some debugging; I don't have access to AWS Code Commit myself, so it's hard to debug. 

When are you getting the TypeError? Can you provide the full traceback?

**Comment by jcejohnson** [comment]
With 2.7 I get the same stacktrace as @WhileLoop. Using dulwich 0.19.10 and master.
With 3.x the type errors are many. I spent a while hacking around them with combinations of str() and encode() but it's a losing battle.
I need 2.7, anyway, because of other dependencies. I'm up for some debugging if you have suggestions. I can't share the repo, unfortunately, because it's on the corporate account.

**Comment by jelmer** [comment]
the TypeError on Python 3 are almost certainly because Dulwich expects bytes rather than strings in most of its lower level APIs.

What would help most to debug this is if you could attach an (unencrypted) network trace using both "git push" and "dulwich push" so we can compare the two. You should be able to do this with

**Comment by jcejohnson** [comment]
With?

**Comment by jelmer** [comment]
Sorry

... with a trivial test repository.

**Comment by TiagoTLD1** [comment]
@jelmer I've been facing the same issue. Diving a bit deeper, the issue isn't strictly on the _handle_receive_pack_tail. Putting logging into the push function, I saw that although the POST in _http_request returns a status 200, it contains no data in the response. For a different client, such as bitbucket, I could see both status 200, data in the response and also the new commit in the cloud. For some reason the aws codecommit isn't accepting the push even if the POST returns 200

**Comment by jelmer** [comment]
What other headers are there in the empty 200 response? I wonder if perhaps AWS is checking for different headers on the POST than Dulwich is setting.

I.e. GitHub used to require that the string "git/" appeared in the User-Agent; AWS may be doing something similar.

**Comment by jelmer** [comment]
This was almost certainly a bug of #739. Please reopen if you can still reproduce this with master or 0.21.
