### ISSUE TITLE
Improve commit comparison documentation

### ISSUE THREAD

**Issue by yakutovicha** [dulwich/dulwich#677]
I am trying to develop an App manager that is based on git. An obvious thing to implement for this kind of manager is to check whether an update is available. This check can be based on a commit comparison.

Having this in mind I tried to do the following (using dulwich of course):
```
In [19]: commit_test_current = repo['refs/heads/develop']

In [20]: commit_test_remote = repo['refs/remotes/origin/develop']

In [21]: commit_test_current < commit_test_remote
Out[21]: True
```
However, a bit later I was surprised that this comparison actually does not have any meaning. According to [this line](https://github.com/dulwich/dulwich/blob/8bbabacd268c3c117df39dda33216ef0b9df8bea/dulwich/objects.py#L533) what actually happens is the comparison of the id strings.

To double-check that  I did the following:
```
In [67]: while(commit.parents):
    ...:     commit_next = repo[commit.parents[0]]
    ...:     print commit_next > commit
    ...:     commit = commit_next
    ...:
    ...:
True
False
True
True
False
False
...
```
I think the right thing to do here would be to either (a) warn a user that this check is meaningless or (b) to implement something more meaningful.

If developers consider (b) as an important thing to have, I would volunteer to open a PR to work on that.

**Comment by yakutovicha** [comment]
Just an idea: a check commit_1 < commit_2 can return:

`True`   - if commit_2 is an ancestor of the commit_1
`False` - if commit_1 is an ancestor of the commit_2
`None` - if the commit_1 and commit_2 are in the diverging branches.

**Comment by yakutovicha** [comment]
also would be nice to put some description here:

https://www.dulwich.io/apidocs/dulwich.objects.Commit.html

**Comment by jelmer** [comment]
Improving the documentation seems like a good idea to me. However, the current behaviour is the one that makes the most sense to me - you want to compare by id e.g. when iterating over all objects in a repository when generating packs.

Checking ancestry in the comparator methods won't work because the object doesn't necessarily come with any history. Checking ancestry is also a much slower operation.

**Comment by jelmer** [comment]
You can use ``Repo.get_walker()`` to check ancestors.

**Comment by jelmer** [comment]
The strings do have a meaning - they're a SHA1 over the contents of the object. This provides a consistent cheaply computable ordering.

The ordering of the objects by id is significant when generating git pack objects; objects in the git pack index are sorted by the id.

**Comment by yakutovicha** [comment]
> The strings do have a meaning - they're a SHA1 over the contents of the object

sure

Alright, if ordering by id is something what people most often do - then we can close the issue (should I make a PR adding the description to make people aware of what is actually compared?).

Still, I feel that making such a comparison explicit would be beneficial for users
```
object.id < object2.id
```
as while reading the code one can immediately understand what is going on.

Also, I think that comparison of the objects should somehow reflect their nature. But this is more philosophical question.

**Comment by jelmer** [comment]
I think that even if we chose another ordering it would always be ambiguous. Would you compare by the contents of the object? By the timestamp? By the topological ordering (and how would you break ties in that case?)?

A pull request to improve the documentation further would be great.

**Comment by yakutovicha** [comment]
For me the topological ordering looks the most interesting. What concerns the algorithm, I would propose the following:

(this is for commits only)
1) Assuming that every pair of connected commits have a directed child <- parent relationship, one could say that commit A < commit B should return `True` if they are connected and B is the parent of A.
2) if there exists a path from A to B and it can be decomposed in a set of child <- parent connections -- then  commit A < commit B is `True` also.
3) if the path from commit A to commit B can be decomposed in a set of parent -> child connections, then commit A < commit B should return `False`.

in all other cases the commit A < commit B should be undefined and `None` should be returned.

examples:
commit A <- commit X1 <- commit X2 <- commit B   |   commit A < commit B (`True`)
commit A <- commit X1 -> commit X2 -> commit B   |   commit A < commit B (`None`)
commit A -> commit X1 -> commit X2 -> commit B   |   commit A < commit B (`False`)

**Comment by jelmer** [comment]
That still doesn't address the issue of performance, or where you're going to find information about the revision graph (a Commit object is not associated with a repository).

**Comment by pstephenson02** [comment]
I'm also interested in this type of functionality. I don't agree with OP that the usage of comparison operators would be obvious to devs, but it would be great if there was an some way to find (if it exists), a common ancestor between 2 commits. Something like [merge-base](https://git-scm.com/docs/git-merge-base).

The use case here for me is given any repo, I would like to be able to programmatically determine if there are upstream changes to HEAD from any remote (usually origin). I was able to do this with native git porcelain commands shown [here](https://stackoverflow.com/a/3278427).

**Comment by jsbain** [comment]
For what it's worth, I have a merge_base function here, that finds the common ancestor(s) for a pair of commits.    https://github.com/jsbain/stash/blob/master/lib/git/gitutils.py

**Comment by pstephenson02** [comment]
@jsbain This is great, thanks. I look forward to trying it out

**Comment by jelmer** [comment]
@pstephenson02 Something like this should tell you whether refs/heads/origin/master has any commits that are not merged into HEAD::
  
    x = Repo('.')
    any(x.get_walker(include=[x[b'refs/remotes/origin/master'].id], exclude=[x[b'HEAD'].id]))
