### ISSUE TITLE
git fetch -p: remove remote-tracking references that no longer exist on the remote

### ISSUE THREAD

**Issue by sheluchin** [dulwich/dulwich#681]
It looks like [`git fetch --prune`](https://git-scm.com/docs/git-fetch#git-fetch---prune) support does not yet exist. It would be a helpful addition. 

Does anyone know if there are any available workarounds?

https://github.com/dulwich/dulwich/blob/72aec0c79fb395689e40f9228df93e2a39cf8fb0/dulwich/porcelain.py#L1095-L1108

**Comment by jelmer** [comment]
Implemented in master.
