### ISSUE TITLE
get_unstaged_changes directory detection is broken in Python 3

### ISSUE THREAD

**Issue by Lothiraldan** [dulwich/dulwich#684]
I have identified a scenario where calling `get_unstaged_changes` in Python 3 could results in a crash. Here is some reproduce steps:

```
git init test
cd test
touch ROOT
git add ROOT
git commit -m "ROOT"
rm ROOT
mkdir ROOT
python -c "import dulwich.repo; import dulwich.index; repo=dulwich.repo.Repo('.'); list(dulwich.index.get_unstaged_changes(repo.open_index(), repo.path))"
```

I think the code is handling this case (here: https://github.com/dulwich/dulwich/blob/master/dulwich/index.py#L634) but the exception seems to have changed in Python 3, it is now a `IsADirectoryError` which is a subclass of `OSError`.

**Comment by jelmer** [comment]
A pull request (ideally with a simple test) to fix this would be great :)
