### ISSUE TITLE
_read_side_band64k_data - string argument expected, got bytes

### ISSUE THREAD

**Issue by carumusan** [dulwich/dulwich#687]
```
File "/env/local/lib/python3.7/site-packages/dulwich/porcelain.py", line 353, in clone
    depth=depth, **kwargs)
  File "/env/local/lib/python3.7/site-packages/dulwich/porcelain.py", line 1115, in fetch
    depth=depth)
  File "/env/local/lib/python3.7/site-packages/dulwich/client.py", line 398, in fetch
    progress=progress, depth=depth)
  File "/env/local/lib/python3.7/site-packages/dulwich/client.py", line 841, in fetch_pack
    progress)
  File "/env/local/lib/python3.7/site-packages/dulwich/client.py", line 660, in _handle_upload_pack_tail
    SIDE_BAND_CHANNEL_PROGRESS: progress}
  File "/env/local/lib/python3.7/site-packages/dulwich/client.py", line 485, in _read_side_band64k_data
    cb(pkt)
TypeError: string argument expected, got 'bytes'
```

**Comment by carumusan** [comment]
Think it's related to this: https://docs.python.org/3/library/sys.html#sys.stderr

"Note To write or read binary data from/to the standard streams, use the underlying binary buffer object. For example, to write bytes to stdout, use sys.stdout.buffer.write(b'abc').
However, if you are writing a library (and do not control in which context its code will be executed), be aware that the standard streams may be replaced with file-like objects like io.StringIO which do not support the buffer attribute."

**Comment by jelmer** [comment]
What platform are you running on?

**Comment by carumusan** [comment]
Google Cloud Function which uses Ubuntu underneath I believe.

**Comment by jelmer** [comment]
Ah, hmm. I guess we have two options:

* Decode the bytestring on the fly and write to sys.stderr
* Use NoneStream (i.e. discard bytestring) if sys.stderr does not have a buffer attribute on Python 3

**Comment by carumusan** [comment]
I guess decoding the bytes to a string would be preferable by default if sys.stderr/out descends from io.TextIOBase. This applies to both default_bytes_out_stream and default_bytes_err_stream.

**Comment by jelmer** [comment]
Yeah, but that's trickier because we have to make assumptions about the encoding or create the streams later in the code.

**Comment by carumusan** [comment]
What encoding does Git use for the progress channel bytes? If it's specified (although from what I've briefly read they have a "the reference code is the spec" standard) couldn't you make that assumption safely? Anyway if it's too tricky then just a simple don't crash fix would be preferable than delaying because of complexity.

**Comment by jelmer** [comment]
The encoding is "whatever the remote server is using", which is not communicated to the client. 

utf-8 is the most common encoding these days, so that would probably be a good guess - but no more than a guess.



On 12 February 2019 09:12:58 GMT, carumusan <notifications@github.com> wrote:
>What encoding does Git use for the progress channel bytes? If it's
>specified (although from what I've briefly read they have a "the
>reference code is the spec" standard) couldn't you make that assumption
>safely? Anyway if it's too tricky then just a simple don't crash fix
>would be preferable than delaying because of complexity.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/dulwich/dulwich/issues/687#issuecomment-462678671

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
