### ISSUE TITLE
HTTP auth with urllib3 does not prompt for credentials

### ISSUE THREAD

**Issue by stephenrkell** [dulwich/dulwich#691]
Since 0.19.0, pushing to a repo with HTTP authentication seems not to work, because it fails with HTTP 401 rather than prompting me for credentials. (I am using dulwich mostly via hg-git version 0.8.12.)

With versions prior to 0.19.0, I see something like the following when pushing to one of my repos.

```
$ hg push git+https://github.com/stephenrkell/liballocs.git
pushing to git+https://github.com/stephenrkell/liballocs.git
http authorization required for https://github.com/stephenrkell/liballocs.git/info/refs
realm: GitHub
user: stephenrkell
password: 
```
whereas from 0.19.0 onwards, I get the following.
```
$ hg push git+https://github.com/stephenrkell/liballocs.git
pushing to git+https://github.com/stephenrkell/liballocs.git
abort: git remote error: unexpected http resp 401 for https://github.com/stephenrkell/liballocs.git/info/refs?service=git-receive-pack
```
As an experiment, I backed out 465addec72ee and 0c99ef824c74 (sorry, Mercurial hashes :-) ) and the problem seems to go away.

Let me know if I can help debug further....

**Comment by stephenrkell** [comment]
The git hashes of those commits are 48e2ef8c2f2c65a33ad3276458791c19ef208c1a and 221f073620265b581d3bf7d4a1eae96ccb469eb9.

**Comment by jelmer** [comment]
Thanks for tracking down that this is the result of the port to urllib3. I don't see an easy way to hook in a password prompt for urllib3; I suspect we'll have to explicitly check for 401 responses, prompt and retry.

**Comment by jelmer** [comment]
After talking to Manuel, we've instead pushed this logic out to clients. I'm adding a separate exception in Dulwich to indicate that the server wanted credentials, allowing the user of Dulwich to retry after e.g. prompting for a password.
