### ISSUE TITLE
Files with CRLF and git configured to convert those to LF leads to incorrect porcelain status

### ISSUE THREAD

**Issue by AndrewLvov** [dulwich/dulwich#693]
If there is a file with Windows newlines (CRLF) and git is set to automatically convert this to unix-style (LF), which is enabled by default (`git config core.autocrlf` option),
```porcelain.status``` with show that that tree is dirty thought no local changes have been made.

[Repo with code to reproduce](https://github.com/AndrewLvov/test_porcelain)

**Comment by jelmer** [comment]
CC @Lothiraldan, who added on the core.autocrlf support in Dulwich.

**Comment by Lothiraldan** [comment]
@AndrewLvov Could you give us your configuration with `git config --list --show-origin`. Please be careful that it might contains sensitive data that you might want to censor.

**Comment by AndrewLvov** [comment]
```file:/home/andrew/.gitconfig    user.name=Andrey
file:/home/andrew/.gitconfig    user.email=registeronsite@gmail.com
file:/home/andrew/.gitconfig    core.editor=vim
file:/home/andrew/.gitconfig    core.excludesfile=/home/andrew/.gitignore_global
file:/home/andrew/.gitconfig    core.autocrlf=input
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=true
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.autocrlf=input
file:.git/config        remote.origin.url=git@github.com:AndrewLvov/test_porcelain.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
```

**Comment by AndrewLvov** [comment]
@Lothiraldan  ^^

**Comment by Lothiraldan** [comment]
I've taken a look at your repository. The file https://github.com/AndrewLvov/test_porcelain/blob/master/test_porcelain/static/crlf.html has been commited with CRLF endings. I've tried various settings for `core.autocrlf` on git in my Windows VM and it seems that git will not alter the line-ending for existing files.

If that's the case, I will need to update dulwich logic to take into account the fact that a file is newly tracked or not.

I will continue digging.

**Comment by AndrewLvov** [comment]
@Lothiraldan The issue is reproducible on Linux, not Windows.
Just in case.

**Comment by Lothiraldan** [comment]
@AndrewLvov I have created a PR that should fix the issue: https://github.com/dulwich/dulwich/pull/704

Could you test it locally and tells me if it worked? You can install the branch with `pip install https://github.com/comet-ml/dulwich/archive/fix-line-ending-convert-new-files.zip`

**Comment by AndrewLvov** [comment]
@Lothiraldan Works now, thanks )
