### ISSUE TITLE
 [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Dima-Kal** [dulwich/dulwich#716]
`  File "C:\Users\dkalinic\source\repos\buzzrauto\py_src\release_manage.py", line 25, in update
    index.build_index_from_tree(local_repo.path, index_file, local_repo.object_store, tree)
  File "C:\Users\dkalinic\AppData\Local\Programs\Python\Python36\lib\site-packages\dulwich\index.py", line 546, in build_index_from_tree
    obj, entry.mode, full_path, honor_filemode=honor_filemode)
  File "C:\Users\dkalinic\AppData\Local\Programs\Python\Python36\lib\site-packages\dulwich\index.py", line 471, in build_file_from_blob
    with open(target_path, 'wb') as f:
PermissionError: [Errno 13] Permission denied: b'.\\lib\\dulwich\\_diff_tree.cp36-win_amd64.pyd'
`

I get this error when trying to update files from repo
Ive tried running it in admin mode and also made sure nothing is using the folder.

**Comment by jelmer** [comment]
I believe this should be fixed - all unit tests now pass on Windows. 

If you can still reproduce this, please reopen and ideally provide a simple script to reproduce it.
