### ISSUE TITLE
Support RefsContainer.__iter__

### ISSUE THREAD

**Issue by jonashaag** [dulwich/dulwich#717]
Reproduce (Python 3.7):

```
mkdir /tmp/testrepo
cd /tmp/testrepo/
git init
touch x
git add x
git commit -m "Initial commit"
```

```
>>> list(dulwich.repo.Repo('/tmp/testrepo').refs)
```

```
TypeError                                 Traceback (most recent call last)
<ipython-input-4-7e07b889cf8d> in <module>
----> 1 list(dulwich.repo.Repo('/tmp/testrepo').refs)

~/dev/klaus/venv3/lib/python3.7/site-packages/dulwich/refs.py in __getitem__(self, name)
    280         This method follows all symbolic references.
    281         """
--> 282         _, sha = self.follow(name)
    283         if sha is None:
    284             raise KeyError(name)

~/dev/klaus/venv3/lib/python3.7/site-packages/dulwich/refs.py in follow(self, name)
    246             references in the chain
    247         """
--> 248         contents = SYMREF + name
    249         depth = 0
    250         refnames = []

TypeError: can't concat int to bytes
```

**Comment by jelmer** [comment]
On Thu, Jul 04, 2019 at 02:11:36AM -0700, Jonas Haag wrote:
> Reproduce:
> 
> ```
> mkdir /tmp/testrepo
> cd /tmp/testrepo/
> git init
> touch x
> git add x
> git commit -m "Initial commit"
> ```
> 
> ```
> >>> list(dulwich.repo.Repo('/tmp/testrepo').refs)
> ```
> 
> ```
> TypeError                                 Traceback (most recent call last)
> <ipython-input-4-7e07b889cf8d> in <module>
> ----> 1 list(dulwich.repo.Repo('/tmp/testrepo').refs)
> 
> ~/dev/klaus/venv3/lib/python3.7/site-packages/dulwich/refs.py in __getitem__(self, name)
>     280         This method follows all symbolic references.
>     281         """
> --> 282         _, sha = self.follow(name)
>     283         if sha is None:
>     284             raise KeyError(name)
> 
> ~/dev/klaus/venv3/lib/python3.7/site-packages/dulwich/refs.py in follow(self, name)
>     246             references in the chain
>     247         """
> --> 248         contents = SYMREF + name
>     249         depth = 0
>     250         refnames = []
> 
> TypeError: can't concat int to bytes
> ```

Thanks.

We don't explicitly support Refs.__iter__ so Python falls back to
calling __getitem__(i) for i in range(...). For convenience we
probably should add __iter__.
