### ISSUE TITLE
load_pack_index throwing FileNotFoundError

### ISSUE THREAD

**Issue by thuctnguyen** [dulwich/dulwich#725]
The code at https://github.com/dulwich/dulwich/blob/master/dulwich/pack.py#L275 assumes that the index file is always there on the filesystem. The assumption is not always true as in the case of "git gc".

The pack files are read and cached in memory. However, the index files are loaded on demand. In the event of a GC, both pack and index files could change. The index files corresponding to the cached pack files may no longer exist on the filesystem.

To maintain consistency the index files should be cached as well.

**Comment by jelmer** [comment]
The function you're linking to is simply the function for loading pack index files. Are you saying that in normal operation, a pack file without matching index file could be present?

**Comment by jelmer** [comment]
Closing this since it's gone for > 6 months without clarification.
