### ISSUE TITLE
Path handling incorrect on Windows

### ISSUE THREAD

**Issue by stmcginnis** [dulwich/dulwich#727]
When looking up paths, the current code expects paths to be splittable on '/':

https://www.dulwich.io/code/dulwich/blob/master/dulwich/objects.py#L-1075

This causes path lookup failures when run on Windows systems where '\' is the path separator.

**Comment by jelmer** [comment]
This is looking up paths in the git tree, where the convention is to use slashes as path separators (even on Windows).

**Comment by stmcginnis** [comment]
Not quite. There are other parts in the code that are just looking at the git metadata, but this one actual does cause failures in expected behavior on Windows.

**Comment by jelmer** [comment]
This particular function isn't looking at filesystem paths; it's possible other parts of the code are passing in Windows paths; they shouldn't.

**Comment by stmcginnis** [comment]
Unfortunate that each consumer needs to know this and the library can't just handle it, but so be it.

**Comment by jelmer** [comment]
This is not a matter of Dulwich not handling it. Backslash is a valid character in Git filenames.

This patch makes it impossible to access such filenames on Windows.

The correct fix is for functions that convert filesystem paths to Git paths to also translate os.sep to b'/'. Most higher level functions in Dulwich should already do this conversion correctly. We'll happily take pull requests to fix any places that don't properly convert between filesystem paths and git paths.
