### ISSUE TITLE
Porcelain pull/push commands can lock up process

### ISSUE THREAD

**Issue by TheLastProject** [dulwich/dulwich#731]
When trying to pull/push something over SSH using `porcelain.pull` or `porselain.push`, Dulwich calls the `SubprocessSSHVendor` which may end up asking for your password on the command line (like for example, to decrypt your SSH key). In my case, the command line isn't visible for the user and thus the porcelain pull/push command may end up "locking up" the entire application.

I'm not sure what the best way to resolve this would be. My first idea was to add `-o BatchMode=yes` to https://github.com/dulwich/dulwich/blob/0dee0a70433f43851ba3cd17411153cd33a26890/dulwich/client.py#L1287, but this would cause a regression for those who do have access to the command line because they will no longer be prompted for a password.

**Comment by jelmer** [comment]
In https://github.com/dulwich/dulwich/pull/689 we discussed adding support for the *GIT_SSH_COMMAND* environment variable. If this were supported, it would allow you to add -oBatchMode=yes for your application. 

Another option is to use the ParamikoSSHClient that lives in dulwich/contrib.

**Comment by TheLastProject** [comment]
Yeah, that could work I'd think.

With regards to using ParamikoSSHClient, I can't seem to find a way to choose that when using a porcelain.pull? Am I missing something there?

**Comment by jelmer** [comment]
Something like this should do it:

    from dulwich.contrib.paramiko_vendor import ParamikoSSHVendor
    dulwich.client.get_ssh_vendor = ParamikoSSHVendor

**Comment by TheLastProject** [comment]
Oh, that helps a lot and throws a nice `paramiko.ssh_exception.PasswordRequiredException: Private key file is encrypted` exception. Thank you!

For me, this "workaround" fixes the issue, so I'll close this issue for now :)
