### ISSUE TITLE
Improperly formatted parameter lists in documentation

### ISSUE THREAD

**Issue by dullbananas** [dulwich/dulwich#732]
![5E3FD7E5-0A3D-42C8-AAFB-CE19E285DF1D](https://user-images.githubusercontent.com/47706471/68516163-845be980-0240-11ea-9165-99d752474018.jpeg)

**Comment by jelmer** [comment]
We're still working on porting the docstrings to Google style, this should hopefully be resolved before the next release.

**Comment by jelmer** [comment]
This should now be complete.
