### ISSUE TITLE
Failed porcelain.clone attempts don't clean up

### ISSUE THREAD

**Issue by Jongy** [dulwich/dulwich#733]
`clone` first creates the local repository. If it fails later, it doesn't clean up, unlike `git clone`.

Well I'm not sure if behavior must match the real `git clone` but I just ran `examples/clone.py` with a bad URL and the initialized repository was left, requiring a manual delete. This funny case, at the very least, should be handled IMO.

**Comment by jelmer** [comment]
Agreed that it would be good to clean up the directory.
