### ISSUE TITLE
Pushing only a new ref (no objects) to a HTTPS repository fails

### ISSUE THREAD

**Issue by brechtm** [dulwich/dulwich#739]
dulwich 0.19.14, CPython 3.7.2, macOS 10.13.6

I'm trying to push a new branch (which points to the same commit as master) to a GitHub repository over HTTPS:

```
from dulwich.repo import MemoryRepo
from dulwich.porcelain import fetch, push

repo = MemoryRepo()
fetch(repo, REMOTE_URL, username=USERNAME, password=PASSWORD)

repo[b'refs/heads/somebranch'] = repo[b'refs/remotes/origin/master']

for ref, sha in repo.refs.as_dict().items():
    print(ref, sha)

push(repo, REMOTE_URL, [b'refs/heads/somebranch'],
     username=USERNAME, password=PASSWORD)

```

After applying #738, this fails with:

> Push to https://github.com/abc/xyz.git failed -> unpack eof before pack header was fully read

I'm not sure whether I'm passing the correct arguments to push, since it's not clear from the reference documentation what's needed exactly. The example in the tutorial doesn't seem to make much sense to me, unfortunately.

I want to do this using the plumbing API eventually. The code below results in the same error:

```
from dulwich.client import get_transport_and_path
from dulwich.repo import MemoryRepo

repo = MemoryRepo()
client, path = get_transport_and_path(REMOTE_URL, username=USERNAME,
                                      password=PASSWORD)

def define_wants(refs):
    return [refs[b'refs/heads/master']]

fetch_result = client.fetch(path, repo, define_wants)
branches = {b'master': fetch_result.refs[b'refs/heads/master']}
repo.refs.import_refs(b'refs/remotes/origin', branches)
repo[b'refs/heads/master'] = repo[b'refs/remotes/origin/master']
print(fetch_result)

repo[b'refs/heads/somebranch'] = repo[b'refs/heads/master']

for ref, sha in repo.refs.as_dict().items():
    print(ref, sha)

def update_refs(refs):
    new_refs = {}
    new_refs[b'refs/heads/somebranch'] = refs[b'refs/heads/master']
    return new_refs

new_refs = client.send_pack(path, update_refs,
                            repo.object_store.generate_pack_data)
```

I'm not sure whether fetching is necessary here (no new objects), but I've included it here just in case.

**Comment by brechtm** [comment]
I just tested pushing a new commit to 'somebranch', and that works. So there's only a problem when pushing only a new ref that references an existing commit.

**Comment by jelmer** [comment]
I think I've found the root cause of this - it's because we're not sending an empty pack when making changes that are not just deletes.

See https://git-scm.com/docs/pack-protocol: "The packfile MUST NOT be sent if the only command used is delete."
