### ISSUE TITLE
0.19.16 release date?

### ISSUE THREAD

**Issue by sijis** [dulwich/dulwich#755]
Hi,

I'm wondering if there is a target release date for the `0.19.16` version?

**Comment by jelmer** [comment]
There is no target date, but I'm happy to do a release soonish if that would be helpful.

**Comment by sijis** [comment]
It would. I'm waiting for the git pull remote changes.

**Comment by jelmer** [comment]
On Wed, Apr 15, 2020 at 08:40:34PM -0700, Sijis Aviles wrote:
> It would. I'm waiting for the git pull remote changes.
I'll try and do a release this weekend.

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by jelmer** [comment]
Done - 0.19.16 is now up on pypi.
