### ISSUE TITLE
issues with typing in python 3.5 that do not seem to exist in python 3.7

### ISSUE THREAD

**Issue by kevinhendricks** [dulwich/dulwich#765]
After a pull from master today, ran a test using a python 3.5.3 version and received the following:

```
LH4057-3970:dul3 kbhend$ python3 ./testmerge.py
Traceback (most recent call last):
  File "./testmerge.py", line 7, in <module>
    from dulwich import porcelain
  File "/Users/kbhend/Desktop/dul3/dulwich/porcelain.py", line 77, in <module>
    from dulwich.client import (
  File "/Users/kbhend/Desktop/dul3/dulwich/client.py", line 104, in <module>
    from dulwich.pack import (
  File "/Users/kbhend/Desktop/dul3/dulwich/pack.py", line 77, in <module>
    from dulwich.objects import (  # noqa: E402
  File "/Users/kbhend/Desktop/dul3/dulwich/objects.py", line 261
    type_name: bytes
             ^
SyntaxError: invalid syntax
LH4057-3970:dul3 kbhend$ python3 --version
Python 3.5.3
```

When tested on python 3.7.2, no errors reported at all!  ;-)   So perhaps full support for static typing did not make it into python 3.5 series.

**Comment by jelmer** [comment]
That should be fixable by using type hints.

Is there a particular reason you need 3.5 (rather than 3.6) support?

**Comment by jelmer** [comment]
Fixed in master.

**Comment by kevinhendricks** [comment]
No, I was just alerting you to the issue.  We embed Pyhton 3.7.x  builds into Sigil for Windows and macOS.  Some Linux distributions may be stuckwith older versions and support back to Python 3.4.x seems typical.

I assumed you wanted to keep Python 3.4 and Python 3.5 compatibility since you just dropped Python 2.7.

Take care,

Kevin

**Comment by jelmer** [comment]
Ah, thanks.

My plan is to drop support for Python < 3.5; there are a number of nice features in 3.5 that I'd like to use, in particular related to asyncio support.

**Comment by kevinhendricks** [comment]
Thanks for the head's up.
