### ISSUE TITLE
FYI: unittest warnings on macOS using Python 3.5.3

### ISSUE THREAD

**Issue by kevinhendricks** [dulwich/dulwich#771]
I wanted to try to exercise the unittest for the latest dulwich master merged into Sigil-Ebook/dulwich master with the proposed merge related changes in place.  I used the following commands:

pip3 install -U pip coverage codecov flake8 fastimport
python3 -m coverage run -p -m unittest dulwich.tests.test_suite

The testsuite ran 1351 tests and reported OK (skipped=66).

But it did generate three warnings, two of which are about unclosed Resources.  
I wanted to pass them along to you in case they were useful.

/Users/kbhend/Desktop/dulwich/dulwich/repo.py:427: 
	UserWarning: ref refs/heads/blah points at non-present sha 1234566789123456789123567891234657373833 UserWarning)

/Users/kbhend/Desktop/dulwich/dulwich/file.py:88: 
	ResourceWarning: unclosed file <_io.FileIO name='local/.git/objects/pack/pack-796a15229c46f4d34d91472ad78d75f2d5377391.pack' mode='rb' closefd=True>
  return io.open(filename, mode, bufsize)

/Users/kbhend/Desktop/dulwich/dulwich/config.py:97: 
	ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, 		 laddr=('127.0.0.1', 49268)>
  return self[key]

If these warnings are expected and/or known and existing on other platforms, please close this.   I only brought this to your attention in case regular testing on macOS was not common.

I was trying to see if the standalone tests I created for diff3merge were actually being invoked.

**Comment by jelmer** [comment]
Thanks. These warnings also happen on other platforms. I'll happily take pull requests to address them, but they're harmless albeit a bit noisy.

FWIW we do have GitHub actions set up for macos/linux/windows, so you can also see the warnings. E.g .for python3.8 on mac: https://github.com/dulwich/dulwich/runs/729300965?check_suite_focus=true
