### ISSUE TITLE
python 2.7 support is broken in dulwich-0.20.2

### ISSUE THREAD

**Issue by shiftycow** [dulwich/dulwich#773]
It looks like Python 2.7 support has been broken in 0.20.2. To replicate:

`pip --version`
> pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

`pip install dulwich`
>...
>Successfully installed certifi-2020.4.5.2 dulwich-0.20.2 urllib3-1.25.9

`python`
>Python 2.7.17 (default, Apr 15 2020, 17:20:14) 
>[GCC 7.5.0] on linux2
>Type "help", "copyright", "credits" or "license" for more information.
>>> 
```py
from dulwich.pack import PackStreamReader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mharris/.local/lib/python2.7/site-packages/dulwich/pack.py", line 77, in <module>
    from dulwich.objects import (  # noqa: E402
  File "/home/mharris/.local/lib/python2.7/site-packages/dulwich/objects.py", line 154
    def object_header(num_type: int, length: int) -> bytes:
                              ^
SyntaxError: invalid syntax
```

`dulwich==0.19.16` seems to be OK.

**Comment by jelmer** [comment]
This is intentional.

Dulwich 0.20 no longer support Python 2.7. See NEWS, README.rst and the announcement on the mailing list (https://groups.google.com/forum/#!topic/dulwich-announce/KiilFsa05uA).
