### ISSUE TITLE
git protocol between client and server fails

### ISSUE THREAD

**Issue by mjpieters** [dulwich/dulwich#781]
It seems something is broken in the git protocol implementation on either the client or the server side. Here is a minimal demonstration:

**Server**

```python
>>> import threading, logging
>>> from dulwich.repo import Repo
>>> from dulwich.server import DictBackend, TCPGitServer
>>> repo = Repo.init("/tmp/testrepo", mkdir=True)
>>> repo.do_commit(b"init", committer=b"Foo Barra <fbarra@example.com>")
b'60249af57f75a0a6936f4a18d49ea2eff7c64545'
>>> backend = DictBackend({b'/': repo})
>>> dul_server = TCPGitServer(backend, b'localhost', 0)
>>> logging.basicConfig(logging.DEBUG)
>>> threading.Thread(target=dul_server.serve).start()
>>> dul_server.socket.getsockname()[1]
63850
>>> INFO:dulwich.server:Handling request from ('127.0.0.1', 63133)
INFO:dulwich.server:Handling b'git-upload-pack' request, args=[b'/', b'host=localhost']
DEBUG:dulwich.server:Opening repository at b'/'
INFO:dulwich.server:Sending capabilities: [b'multi_ack_detailed', b'multi_ack', b'side-band-64k', b'thin-pack', b'ofs-delta', b'no-progress', b'include-tag', b'shallow', b'no-done', b'symref=HEAD:refs/heads/master']
INFO:dulwich.server:Client capabilities: [b'multi_ack', b'multi_ack_detailed', b'ofs-delta', b'shallow', b'side-band-64k', b'thin-pack']
INFO:dulwich.server:Handling request from ('127.0.0.1', 63275)
INFO:dulwich.server:Handling b'git-upload-pack' request, args=[b'/', b'host=localhost']
DEBUG:dulwich.server:Opening repository at b'/'
INFO:dulwich.server:Sending capabilities: [b'multi_ack_detailed', b'multi_ack', b'side-band-64k', b'thin-pack', b'ofs-delta', b'no-progress', b'include-tag', b'shallow', b'no-done', b'symref=HEAD:refs/heads/master']
INFO:dulwich.server:Client capabilities: [b'multi_ack', b'multi_ack_detailed', b'ofs-delta', b'shallow', b'side-band-64k', b'thin-pack']
```

**Client**

```python
>>> from dulwich import porcelain
>>> remote = "git://localhost:63850/"
>>> repo = porcelain.clone(remote, '/tmp/clientside', checkout=True)
counting objects: 2, done.
Checking out 60249af57f75a0a6936f4a18d49ea2eff7c64545
>>> repo
<Repo at '/tmp/clientside'>
>>> porcelain.pull(repo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../lib/python3.6/site-packages/dulwich/porcelain.py", line 991, in pull
    path, r, progress=errstream.write, determine_wants=determine_wants)
  File "/.../lib/python3.6/site-packages/dulwich/client.py", line 432, in fetch
    progress=progress, depth=depth)
  File "/.../lib/python3.6/site-packages/dulwich/client.py", line 916, in fetch_pack
    progress)
  File "/.../lib/python3.6/site-packages/dulwich/client.py", line 715, in _handle_upload_pack_tail
    pkt = proto.read_pkt_line()
  File "/.../lib/python3.6/site-packages/dulwich/protocol.py", line 212, in read_pkt_line
    raise HangupException()
dulwich.errors.HangupException: The remote server unexpectedly closed the connection.
```

I'm using dulwich 0.20.3 on both sides.

**Comment by mjpieters** [comment]
Another data point: this is on Mac OS X 10.13. I don't think it makes a difference for this specific test but you never know.

**Comment by jelmer** [comment]
On Wed, Jun 17, 2020 at 01:56:55PM -0700, Martijn Pieters wrote:
> Another data point: this is on Mac OS X 10.13. I don't think it makes a difference for this specific test but you never know.
Thanks.

I wonder if this is a regression in 0.20.3, where I changed some of
this logic. Apparently the test coverage is a bit lacking in one
corner case or another..

I think we should:

 1) add a test for this to the compat testsuite (which runs the
    Dulwich client against C Git server)
 2) fix the client to pass
 3) fix the server if necessary


-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by mjpieters** [comment]
I tried to bisect this issue, but I actually can't find a dulwich release on which this *did* work. Here's my test script:

```python
import os
import tempfile
import threading

from dulwich import porcelain
from dulwich.repo import Repo
from dulwich.server import DictBackend, TCPGitServer

with tempfile.TemporaryDirectory() as td:
    serverrepo = Repo.init(os.path.join(td, "serverrepo"), mkdir=True)
    serverrepo.do_commit(b"init", committer=b"Foo Barra <fbarra@example.com>")
    backend = DictBackend({b'/': serverrepo})
    dul_server = TCPGitServer(backend, b'localhost', 0)
    try:
        threading.Thread(target=dul_server.serve).start()
        port = dul_server.socket.getsockname()[1]

        remote = f"git://localhost:{port}/"
        repo = porcelain.clone(remote, os.path.join(td, "clientrepo"), checkout=True)
        porcelain.pull(repo, remote)
    finally:
        dul_server.shutdown()
```

and a short shell script (made executable):

```sh
#!/bin/sh
echo 'building extensions'
make clean && make all
echo 'testing client-server interaction'
python client_server_pull.py
```

I tested on `dulwich-0.17.0`, `dulwich-0.18.0`, `dulwich-0.19.0`, `dulwich-0.20.0`, and in all cases the `dulwich.errors.HangupException: The remote server unexpectedly closed the connection.` exception is thrown.

**Comment by jelmer** [comment]
On Thu, Jun 18, 2020 at 03:49:43AM -0700, Martijn Pieters wrote:
> I tried to bisect this issue, but I actually can't find a dulwich release on which this *did* work. Here's my test script:
> 
> ```python
> import os
> import tempfile
> import threading
> 
> from dulwich import porcelain
> from dulwich.repo import Repo
> from dulwich.server import DictBackend, TCPGitServer
> 
> with tempfile.TemporaryDirectory() as td:
>     serverrepo = Repo.init(os.path.join(td, "serverrepo"), mkdir=True)
>     serverrepo.do_commit(b"init", committer=b"Foo Barra <fbarra@example.com>")
>     backend = DictBackend({b'/': serverrepo})
>     dul_server = TCPGitServer(backend, b'localhost', 0)
>     try:
>         threading.Thread(target=dul_server.serve).start()
>         port = dul_server.socket.getsockname()[1]
> 
>         remote = f"git://localhost:{port}/"
>         repo = porcelain.clone(remote, os.path.join(td, "clientrepo"), checkout=True)
>         porcelain.pull(repo, remote)
>     finally:
>         dul_server.shutdown()
> ```
> 
> and a short shell script (made executable):
> 
> ```sh
> #!/bin/sh
> echo 'building extensions'
> make clean && make all
> echo 'testing client-server interaction'
> python client_server_pull.py
> ```
> 
> I tested on `dulwich-0.17.0`, `dulwich-0.18.0`, `dulwich-0.19.0`, `dulwich-0.20.0`, and in all cases the `dulwich.errors.HangupException: The remote server unexpectedly closed the connection.` exception is thrown.

I've made some progress on this. It looks like part of the issue is
that the dulwich client and the C Git client behave differently.

The Dulwich client will tell the server during the clone phase that it
wants to retrieve the HEAD ref (which it already has). This is a
minor bug in Dulwich - since it could avoid fetching this ref.

The Dulwich server doesn't send back an empty pack in all cases if the
client doesn't hang up but in some cases it hangs up. Instead, it
should follow the pack protocol and only hang up if the client tells
it that it's done.

The following patch fixes the issue, although it doesn't really deal
with stateless RPCs yet:

diff --git a/dulwich/server.py b/dulwich/server.py
index 7a4e1859..7edbdb14 100644
--- a/dulwich/server.py
+++ b/dulwich/server.py
@@ -364,15 +364,6 @@ class UploadPackHandler(PackHandler):
         # band) will be be considered a fatal error.
         self._processing_have_lines = True

-        # Did the process short-circuit (e.g. in a stateless RPC call)? Note
-        # that the client still expects a 0-object pack in most cases.
-        # Also, if it also happens that the object_iter is instantiated
-        # with a graph walker with an implementation that talks over the
-        # wire (which is this instance of this class) this will actually
-        # iterate through everything and write things out to the wire.
-        if len(objects_iter) == 0:
-            return
-
         # The provided haves are processed, and it is safe to send side-
         # band data now.
         self._processing_have_lines = False


Jelmer

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc
