### ISSUE TITLE
repo.BaseRepo.do_commit() does not use committer when author is omitted

### ISSUE THREAD

**Issue by mjpieters** [dulwich/dulwich#786]
As of a65b1c79ffbd8922305fd9263c8728def17fb5eb, `do_commit()` no longer sets `author` to `committer` if not explicitly set. However, the docstring still claims this is the case:

https://github.com/dulwich/dulwich/blob/ba79362c88dc1e9b633d4b2ef78238d2f1ae28e8/dulwich/repo.py#L783

Either the claim should be removed or the old behaviour should be re-instated.

**Comment by jelmer** [comment]
Thanks for the report. It's meant to behave similarly to C Git, so I believe the docstring is wrong. I'll push a fix.
