### ISSUE TITLE
Long refs names get looked up first in object_store

### ISSUE THREAD

**Issue by Wiguwbe** [dulwich/dulwich#791]
Refs with names with length 20 or 40 get looked up first in object store and then in refs.

https://github.com/dulwich/dulwich/blob/8abe4b3d92344893e5fb6e3385172ef94b5fbf11/dulwich/repo.py#L730

This raises an `binascii.Error: Non-hexadecimal digit found`, which is not caught and the `name in self.refs` is never run.

I'd suggest either check if the string is hexadecimal, and if it is, also look up in the object_store, or catching the exception somewhere *along the way*:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/test/dulwich/dulwich/repo.py", line 730, in __contains__
    return name in self.object_store or name in self.refs
  File "/home/user/test/dulwich/dulwich/object_store.py", line 347, in __contains__
    if self.contains_packed(sha) or self.contains_loose(sha):
  File "/home/user/test/dulwich/dulwich/object_store.py", line 336, in contains_packed
    if sha in pack:
  File "/home/user/test/dulwich/dulwich/pack.py", line 2017, in __contains__
    self.index.object_index(sha1)
  File "/home/user/test/dulwich/dulwich/pack.py", line 400, in object_index
    sha = hex_to_sha(sha)
  File "/home/user/test/dulwich/dulwich/objects.py", line 110, in hex_to_sha
    return binascii.unhexlify(hex)
binascii.Error: Non-hexadecimal digit found

```

I'm currently using version 0.20.5 from PyPi, although, this traceback is from the current master branch (8abe4b3d92344893e5fb6e3385172ef94b5fbf11).

I can and be glad to fix this and open a Pull Request, I'm just not sure if any of my suggestions are the way to go.

**Comment by Wiguwbe** [comment]
Since the chance of being of lenght 20 ou 40 seems to be low (I think), matching with a regex could be easy?

```
# (...)
import re
# (...)
re_ishexadecimal = re.compile('^[a-fA-F0-9]+$')
# (...)
        if len(name) in (20,40):
            return name in self.refs or (re_ishexadecimal.match(name) is not None and name in self.object_store)
```

or something more readable perhaps.

**Comment by jelmer** [comment]
Thanks, a pull request would be great.

I think we'd want to change the check to:
          if len(name) == 20 or (len(name) == 40 and valid_hexsha(name)):

(valid_hexsha lives in dulwich.objects)

The check for len(name) == 40 to avoid calling valid_hexsha unnecessarily.

**Comment by Wiguwbe** [comment]
Thanks for the tip!

Seems to have been fixed:
```
Python 3.8.3 (default, May 14 2020, 11:03:12) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dulwich.porcelain
>>> r = dulwich.porcelain.Repo('.')
>>> b'refs/remotes/origin/feature/self-compile' in r
False
>>> len(b'refs/remotes/origin/feature/self-compile')
40
>>> dulwich
<module 'dulwich' from '/home/user/dulwich/dulwich/__init__.py'>
```

Branch doesn't exist, which is normal, but doesn't raise the exception

**Comment by jelmer** [comment]
Merged, thanks!
