### ISSUE TITLE
support for configuration proxy in environment variables

### ISSUE THREAD

**Issue by zogzog** [dulwich/dulwich#797]
In the current master, dulwich does not honour the proxy settings.

We observe a timeout when pulling. 
Using strace we can catch the blocked socket call on the pristine repo url (rather than the proxy).

An immediate workaround will be:

```diff --git a/dulwich/client.py b/dulwich/client.py
index 9453b13a..9a76768a 100644
--- a/dulwich/client.py
+++ b/dulwich/client.py
@@ -1480,7 +1480,7 @@ def default_urllib3_manager(config, pool_manager_cls=None,
         try:
             proxy_server = config.get(b"http", b"proxy")
         except KeyError:
-            pass
+            proxy_server = os.environ.get('https_proxy')
         try:
             user_agent = config.get(b"http", b"useragent")
         except KeyError:
```

By the way, why is there no such fallback ? It would be generally useful when e.g. dulwich is used in conjunction with hg-git and with proper proxy setup in the environment.

**Comment by jelmer** [comment]
A pull request to add support for proxy configuration environment variables would be very welcome; we'd probably want to follow the behaviour in C Git: https://github.com/git/git/blob/master/http.c#L1022

**Comment by zogzog** [comment]
Why not a PR but I don't understand your suggestion. I'd do it as written in my snippet (I don't know better).

**Comment by jelmer** [comment]
Alternatively, feel free to just post the patch and I can import it into Git.

**Comment by zogzog** [comment]
Ok, I wanted to publish this:

```diff
commit d0a5a9c4f493b51016f6e9e71d52da1cab942bae (HEAD -> master, use_env_proxy)
Author: aurelien <aurelien.campeas@pythonian.fr>
Date:   Fri Aug 21 18:22:48 2020 +0200

    client: fetch proxy info from the environment
    
    Closes #797.

diff --git a/dulwich/client.py b/dulwich/client.py
index 9453b13a..4a9c2af2 100644
--- a/dulwich/client.py
+++ b/dulwich/client.py
@@ -1480,7 +1480,10 @@ def default_urllib3_manager(config, pool_manager_cls=None,
         try:
             proxy_server = config.get(b"http", b"proxy")
         except KeyError:
-            pass
+            for proxyname in ('https_proxy', 'http_proxy', 'all_proxy'):
+                proxy_server = os.environ.get(proxyname)
+                if proxy_server is not None:
+                    break
         try:
             user_agent = config.get(b"http", b"useragent")
         except KeyError:
diff --git a/dulwich/tests/test_client.py b/dulwich/tests/test_client.py
index 9816d2b3..b5135857 100644
--- a/dulwich/tests/test_client.py
+++ b/dulwich/tests/test_client.py
@@ -1108,6 +1108,18 @@ class DefaultUrllib3ManagerTest(TestCase):
         self.assertEqual(manager.proxy.host, 'localhost')
         self.assertEqual(manager.proxy.port, 3128)
 
+    def test_environment_proxy(self):
+        import urllib3
+        config = ConfigDict()
+        os.environ['http_proxy'] = 'http://myproxy:8080'
+        manager = default_urllib3_manager(config=config)
+        self.assertIsInstance(manager, urllib3.ProxyManager)
+        self.assertTrue(hasattr(manager, 'proxy'))
+        self.assertEqual(manager.proxy.scheme, 'http')
+        self.assertEqual(manager.proxy.host, 'myproxy')
+        self.assertEqual(manager.proxy.port, 8080)
+        del os.environ['http_proxy']
+
     def test_config_proxy_custom_cls(self):
         import urllib3
 
```

**Comment by zogzog** [comment]
Or as joined.
[dulwich.patch.gz](https://github.com/dulwich/dulwich/files/5161211/dulwich.patch.gz)

(beware the embedded node ids come from hg-git)

**Comment by jelmer** [comment]
On Wed, Sep 02, 2020 at 02:11:27AM -0700, Aurélien Campéas wrote:
> Or as joined.
> [dulwich.patch.gz](https://github.com/dulwich/dulwich/files/5161211/dulwich.patch.gz)
> 
> (beware the embedded node ids come from hg-git)
That change looks a bit odd to me. Doesn't this mean that it will only
look at the environment variables if a git configuration file is
present and specified?

Jelmer

**Comment by zogzog** [comment]
Why makes you suspect so ?

**Comment by jelmer** [comment]
If you pass in None as config to default_urllib3_manager(), the environment will be ignored as far as I can tell.

**Comment by zogzog** [comment]
Yes, indeed. All I can say is that from within hg-git, as I observed it, it is not None. I don't know the circumstances under which it can be None (clone time + no global git config maybe ?).

I can move the relevant hunk out of there if you prefer so.

**Comment by zogzog** [comment]
Here it is.

[patch.gz](https://github.com/dulwich/dulwich/files/5163559/patch.gz)

**Comment by jelmer** [comment]
Applied, thanks!
