### ISSUE TITLE
Unable to supply a private key to ParamikoSSHVendor

### ISSUE THREAD

**Issue by larstobi** [dulwich/dulwich#800]
I am trying to use `dulwich` with the `ParamikoSSHVendor` in an environment where I have no `ssh` binary and I cannot add a private key to the disk, I can only supply a private key in memory.

I am able to make the connection work with a private key in memory using only `paramiko`, but when I try to make `dulwich` work with `ParamikoSSHVendor` I am not able to figure out how to supply a private key to it.

```python
from dulwich.client import get_transport_and_path_from_url
from dulwich import client as _mod_client
from dulwich.contrib.paramiko_vendor import ParamikoSSHVendor

_mod_client.get_ssh_vendor = ParamikoSSHVendor
remote = "ssh://git@github.com:22/owner/repo.git"
client, path = get_transport_and_path_from_url(remote)
```

ParamikoSSHVendor takes `pkey` as a keyword argument, but I am not able to supply it.
Here is a reference to the code: https://github.com/dulwich/dulwich/blob/master/dulwich/contrib/paramiko_vendor.py#L82

If I try this:
```python
import paramiko
from io import StringIO
deploy_key = "private key provided securely"
pkey = paramiko.RSAKey.from_private_key(StringIO(deploy_key))
client, path = get_transport_and_path_from_url(remote, pkey=pkey)
```
then I get the following error:
```
TypeError: __init__() got an unexpected keyword argument 'pkey'
```

If I try this:
```python
    client.ssh_kwargs['pkey'] = pkey
```
then I get the following error:
```
AttributeError: 'SSHGitClient' object has no attribute 'ssh_kwargs'
```

Is it even possible to do this? If so, can somebody help me out with an example?

**Comment by jelmer** [comment]
pkey is an argument to the ParamikoSSHVendor. Something like this should work:

get_transport_and_path_from_url(remote, vendor=ParamikoSSHVendor(pkey=pkey))

**Comment by larstobi** [comment]
Thanks, it worked right away! 👍
