### ISSUE TITLE
Traceback due to calling encode

### ISSUE THREAD

**Issue by osbugs** [dulwich/dulwich#804]
I was currently plagued by a failure in the Mercurial hg-ext extension as pointed out in a [hg-git bug report](https://foss.heptapod.net/mercurial/hg-git/-/issues/329) (not reported by me).

It was not difficult to find the [source of the traceback](https://github.com/dulwich/dulwich/blob/5c8b3272a5e864977214ad382e04ce65ac9642f9/dulwich/client.py#L1048): Removing the call to encode solved the issue for me.

I don't understand too much of Python so I don't know how a proper fix should look like this is why I am opening the bug report. Thank you for your consideration!

**Comment by jelmer** [comment]
On Thu, Oct 15, 2020 at 02:32:55AM -0700, osbugs wrote:
> I was currently plagued by a failure in the Mercurial hg-ext extension as pointed out in a [hg-git bug report](https://foss.heptapod.net/mercurial/hg-git/-/issues/329) (not reported by me).
> 
> It was not difficult to find the [source of the traceback](https://github.com/dulwich/dulwich/blob/5c8b3272a5e864977214ad382e04ce65ac9642f9/dulwich/client.py#L1048): Removing the call to encode solved the issue for me.
> 
> I don't understand too much of Python so I don't know how a proper fix should look like this is why I am opening the bug report. Thank you for your consideration!

This looks like a bug in hg-git to me - it's passing in host as a
bytestring whereas it should be a regular string (which would have an
encode attribute).

Jelmer

-- 
Jelmer Vernooĳ <jelmer@jelmer.uk>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by jelmer** [comment]
Closing since this is a hg-git bug - happy to help if you need details.

**Comment by osbugs** [comment]
Thanks for your help. I intend to file a bug with hg-git but I do not have an account on their Gitlab yet.
