### ISSUE TITLE
Remote archive doesn't work. "invalid response ACK"

### ISSUE THREAD

**Issue by DzmitrySudnik** [dulwich/dulwich#805]
Looks like the code expects "ACK\n" but gets just "ACK" and fails. Maybe it's related to my own hosted gerrit, however as the shell git works fine with it, I think the dulwich needs to support that too.

**Comment by jelmer** [comment]
That makes sense. A pull request to remove the trailing newline (in both server and client) would be great, if you're in a position to do that.

**Comment by DzmitrySudnik** [comment]
@jelmer yep, please take a look at #806
