### ISSUE TITLE
No binary Linux wheels on PyPI

### ISSUE THREAD

**Issue by danchr** [dulwich/dulwich#826]
It would be great if Dulwich could provide `manylinux1` wheels, for example using [`cibuildwheel`](https://github.com/joerick/cibuildwheel), as this would enable installation on Linux without requiring Python headers.

**Comment by danchr** [comment]
I was wrong; latest release does indeed have wheels:

https://pypi.org/project/dulwich/#files

**Comment by jelmer** [comment]
On Mon, Dec 21, 2020 at 04:54:25AM -0800, Dan Villiom Podlaski Christiansen wrote:
> I was wrong; latest release does indeed have wheels:
> 
> https://pypi.org/project/dulwich/#files

We only recently started publishing wheels. One of the recent releases
missed manylinux wheels due to a bug in the GitHub action we're using
to build manylinux wheels.

Jelmer
