### ISSUE TITLE
Trying to clone remote repo using pub/private keys from string

### ISSUE THREAD

**Issue by ArtemBernatskyy** [dulwich/dulwich#844]
Hi, how can we clone a remote repo using pub/private keys from strings or as files (but not from standard location)?

For now I'm able to clone `public` repo using
`porcelain.clone(source=remote_url, target=target)`

but I need to somehow clone `private` repo via specifying ssh keys (as strings, or via providing path to files)

Thx!

**Comment by jelmer** [comment]
You can use your regular ssh configuration for this. Alternatively, you can use the ParamikoSSHVendor (see dulwich.contrib.paramiko_ssh_vendor).

**Comment by jelmer** [comment]
(In general, please use e.g. stackoverflow or the mailing list for questions rather than the GitHub bug tracker)

**Comment by ArtemBernatskyy** [comment]
@jelmer usually I'm using that, but after spending like 2-3 hours trying to find a WORKING example I gave up and wrote here,

it will be very helpful to find a working example of using non-standart location for ssh keys, thx.
