### ISSUE TITLE
Docs disappeared

### ISSUE THREAD

**Issue by inducer** [dulwich/dulwich#845]
Both links to documentation at https://dulwich.io/ now return 404:

- https://dulwich.io/docs/api/
- https://dulwich.io/docs

In addition to the obvious effects, it also breaks my downstream CI: https://gitlab.tiker.net/inducer/relate/-/jobs/236287 :)

**Comment by jelmer** [comment]
should be fixed now

**Comment by inducer** [comment]
Thanks!
