### ISSUE TITLE
TortoiseHg is crashing with the plugin.

### ISSUE THREAD

**Issue by MichaeINeumann** [dulwich/dulwich#858]
Hello, I hope every can help me.

![grafik](https://user-images.githubusercontent.com/81390813/112824200-8b300a00-908a-11eb-8755-004c65c82dba.png)
![grafik](https://user-images.githubusercontent.com/81390813/112824228-92efae80-908a-11eb-8b83-93b8b51500bc.png)
![grafik](https://user-images.githubusercontent.com/81390813/112824266-9e42da00-908a-11eb-86e2-1a2822142fe6.png)

**Comment by jelmer** [comment]
Please follow up in tortoisehg, it looks like it's using an old python version (2.7) with a new dulwich. This is not a bug in Dulwich.

**Comment by MichaeINeumann** [comment]
Many Thanks for the quick response.
