### ISSUE TITLE
porcelain.status(): reports unmodified files as containing unstaged changes on Windows

### ISSUE THREAD

**Issue by pmrowla** [dulwich/dulwich#865]
On Windows, `porcelain.status()` shows all files as changed even when the working tree and index should both be clean.

```
(.venv-win) PS C:\users\vagrant\example-get-started> git ls-files
.dvc/.gitignore
.dvc/config
.dvc/plots/confusion.json
.dvc/plots/confusion_normalized.json
.dvc/plots/default.json
.dvc/plots/linear.json
.dvc/plots/scatter.json
.dvc/plots/smooth.json
.dvcignore
.gitignore
README.md
data/.gitignore
data/data.xml.dvc
dvc.lock
dvc.yaml
params.yaml
prc.json
roc.json
scores.json
src/evaluate.py
src/featurization.py
src/prepare.py
src/requirements.txt
src/train.py
(.venv-win) PS C:\users\vagrant\example-get-started> git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
(.venv-win) PS C:\users\vagrant\example-get-started> pip freeze
certifi==2020.12.5
dulwich==0.20.21
urllib3==1.26.4
(.venv-win) PS C:\users\vagrant\example-get-started> python
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from dulwich import porcelain
>>> porcelain.status(".")
GitStatus(staged={'add': [], 'delete': [], 'modify': []}, unstaged=[b'.dvc/.gitignore', b'.dvc/config', b'.dvc/plots/confusion.json', b'.dvc/plots/confusion_normalized.json', b'.dvc/plots/default.json', b'.dvc/plots/linear.json', b'.dvc/plots/scatter.json', b'.dvc/plots/smooth.json', b'.dvcignore', b'.gitignore', b'README.md', b'data/.gitignore', b'data/data.xml.dvc', b'dvc.lock', b'dvc.yaml', b'params.yaml', b'prc.json', b'roc.json', b'scores.json', b'src/evaluate.py', b'src/featurization.py', b'src/prepare.py', b'src/requirements.txt', b'src/train.py'], untracked=[])

```

For reference, this is using a completely fresh clone (via CLI `git clone`) of https://github.com/iterative/example-get-started. I tested in `0.20.21` and current master and got the same result.

**Comment by pmrowla** [comment]
actually this is probably a duplicate of https://github.com/dulwich/dulwich/issues/693

@jelmer should I just try to clean up https://github.com/dulwich/dulwich/pull/704?

**Comment by jelmer** [comment]
Yeah, that would be great.

**Comment by pmrowla** [comment]
Testing this some more, it looks to me like dulwich's crlf normalization is already working properly in master. The problem seems to be with dulwich not reading `core.autocrlf` from global/system configs:

If `core.autocrlf` is set outside of the repo, I get the incorrect status (I added print statements to show the read config values in `dulwich/line_endings.py:BlobNormalizer.__init__()`)

```
(.venv-win) PS C:\Users\vagrant\example-get-started> git config --show-origin core.autocrlf
file:C:/Program Files/Git/etc/gitconfig true
(.venv-win) PS C:\Users\vagrant\example-get-started> python
Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  4 2021, 13:27:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from dulwich import porcelain
>>> porcelain.status()
core.eol native
core.autocrlf False
GitStatus(staged={'add': [], 'delete': [], 'modify': []}, unstaged=[b'.dvc/.gitignore', b'.dvc/config', b'.dvc/plots/confusion.json', b'.dvc/plots/confusion_normalized.json', b'.dvc/plots/default.json', b'.dvc/plots/linear.json', b'.dvc/plots/scatter.json', b'.dvc/plots/smooth.json', b'.dvcignore', b'.gitignore', b'README.md', b'data/.gitignore', b'data/data.xml.dvc', b'dvc.lock', b'dvc.yaml', b'params.yaml', b'prc.json', b'roc.json', b'scores.json', b'src/evaluate.py', b'src/featurization.py', b'src/prepare.py', b'src/requirements.txt', b'src/train.py'], untracked=[])
```

If I explicitly set `core.autocrlf` in the repo, it works properly
```
(.venv-win) PS C:\Users\vagrant\example-get-started> git config core.autocrlf true
(.venv-win) PS C:\Users\vagrant\example-get-started> git config --show-origin core.autocrlf
file:.git/config        true
(.venv-win) PS C:\Users\vagrant\example-get-started> python
Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  4 2021, 13:27:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from dulwich import porcelain
>>> porcelain.status()
core.eol native
core.autocrlf b'true'
GitStatus(staged={'add': [], 'delete': [], 'modify': []}, unstaged=[], untracked=[])
```

```
(.venv-win) PS C:\Users\vagrant\example-get-started> git config core.autocrlf input
(.venv-win) PS C:\Users\vagrant\example-get-started> python
Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  4 2021, 13:27:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from dulwich import porcelain
>>> porcelain.status()
core.eol native
core.autocrlf b'input'
GitStatus(staged={'add': [], 'delete': [], 'modify': []}, unstaged=[], untracked=[])
```

**Comment by pmrowla** [comment]
It looks like the confusion over new-files in #704 because the issue in #693 was specifically about using `core.autocrlf=input` to correct files which have been committed with `CRLF` to `LF`. 
The changes in #704 are trying to fix a non-existent (in current master) issue with `core.autocrlf=true`.

(from the git docs)
> If you’re on a Linux or macOS system that uses LF line endings, then you don’t want Git to automatically convert them when you check out files; however, if a file with CRLF endings accidentally gets introduced, then you may want Git to fix it. You can tell Git to convert CRLF to LF on commit but not the other way around by setting core.autocrlf to input:

I'll probably do one PR to read the system config (for this bug report), and a separate one to address the `core.autocrlf=input` issue in #693.

**Comment by pmrowla** [comment]
I guess checking for the system config on windows isn't exactly straightforward since it depends on where the user installed Git (it will be in `<path-to-git-installation>/etc/gitconfig`

But it reasonable for dulwich to at least check `C:/Program Files/Git/etc/gitconfig` (current default Git for Windows install location) and `C:\ProgramData\Git\config` (alternate system config location in vista+ from the [git docs](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup))
