### ISSUE TITLE
`porcelain.stash_pop`: Missing one required positional argument, `index`

### ISSUE THREAD

**Issue by personalizedrefrigerator** [dulwich/dulwich#876]
## Summary
 * `porcelain.stash_pop` does not provide dulwich.stash.Stash::pop with a required argument.

https://github.com/dulwich/dulwich/blob/642d726c8c2f61b1514b52868e13014452ec263c/dulwich/porcelain.py#L1810-L1817

## Details
```
File "/var/mobile/Containers/Data/Application/E9B0787A-B16E-45E0-9A4B-91195CFA13CF/
Documents/bin/git", line 165, in run
    porcelain.stash_pop(repo)
  File "/var/mobile/Containers/Data/Application/E9B0787A-B16E-45E0-9A4B-91195CFA13CF/
Library/lib/python3.9/site-packages/dulwich/porcelain.py", line 1783, in stash_pop
    stash.pop()
TypeError: pop() missing 1 required positional argument: 'index'
```

Note that the line numbers in the error message don't match those in the current repository; I'm using `dulwich`, as available via `PyPI`.

**Comment by jelmer** [comment]
On Sun, May 30, 2021 at 11:20:53AM -0700, Henry Heino wrote:
> ## Summary
>  * `porcelain.stash_pop` does not provide dulwich.stash.Stash::pop with a required argument.
> 
> https://github.com/dulwich/dulwich/blob/642d726c8c2f61b1514b52868e13014452ec263c/dulwich/porcelain.py#L1810-L1817
> 
> 
> ## Details
> ```
> File "/var/mobile/Containers/Data/Application/E9B0787A-B16E-45E0-9A4B-91195CFA13CF/
> Documents/bin/git", line 165, in run
>     porcelain.stash_pop(repo)
>   File "/var/mobile/Containers/Data/Application/E9B0787A-B16E-45E0-9A4B-91195CFA13CF/
> Library/lib/python3.9/site-packages/dulwich/porcelain.py", line 1783, in stash_pop
>     stash.pop()
> TypeError: pop() missing 1 required positional argument: 'index'
> ```
> 
> Note that the line numbers in the error message don't match those in the current repository; I'm using `dulwich`, as available via `PyPI`.

I've fixed this specific issue. However, Stash.pop() is currently not
implemented (that would require support for updating the working
tree).

You can use stash_drop() to drop stashes without applying them to the
working tree.

-- 
Jelmer Vernooĳ ***@***.***>
PGP Key: https://www.jelmer.uk/D729A457.asc
