### ISSUE TITLE
Documentation for `stash.Stash`: How to update the working tree?

### ISSUE THREAD

**Issue by personalizedrefrigerator** [dulwich/dulwich#877]
The [stash.Stash::push](https://www.dulwich.io/docs/api/dulwich.stash.html) documentation currently states `Note that this doesn’t currently update the working tree.`. It would be very helpful if it suggested/linked to a way to update the working tree!

Even if this isn't added, it would be nice if `cli.py` updated the working tree after calls to `stash push` or `stash pop`! I've been using `cli.py` and `porcelain.py` as example code for using `dulwich`, so this could be an alternate way to document this!

**Comment by jelmer** [comment]
There is currently no way to merge changes into the working tree, other than to create the working tree from scratch. See #452 for the main bug about this.

**Comment by jelmer** [comment]
I'm still quite keen on getting the working tree merge fixes landed, it's the main missing feature in Dulwich today.
