### ISSUE TITLE
space chars at start of .gitignore

### ISSUE THREAD

**Issue by gtors** [dulwich/dulwich#878]
If .gitignore starts with `20 20 0a` (in hex), then dulwich will read it as `Pattern(b"", False)`

![image](https://user-images.githubusercontent.com/9943520/120120008-7ca5c200-c1a3-11eb-9e2e-4011807f8098.png)

So, this cause some strange bug for me, for example my dir `app/web` become ignorable, but in reality it is not. 

In my case, dulwich was used as dependency of DVC tool (https://github.com/iterative/dvc/blob/7700d555296e52564dd27d767406104c994e42c1/dvc/scm/git/backend/dulwich.py#L281)

Seems, that function doesn't  handle situation than line contains only space chars https://github.com/dulwich/dulwich/blob/76dd8356f9d8870f44226e4232c24fbc1e573e93/dulwich/ignore.py#L114-L140

**Comment by gtors** [comment]
```python
line = b"  \n"
line.rstrip(b"\r\n") 
```
line will be `b"  "` here

**Comment by jelmer** [comment]
Any chance you can add a test case for this to dulwich/tests/test_ignore.py ? that should be fairly straightforward to do; a proper fix would also be great, but I'm also happy to take it from there.

**Comment by gtors** [comment]
Ok, I will try.
