### ISSUE TITLE
dulwich client got 404 on git https service from sourceforge.net

### ISSUE THREAD

**Issue by alexrayne** [dulwich/dulwich#897]
Hallow!

i try import git repo from https://sourceforge.net/p/ion-dtn/open-source/ci/main/tree/ with latest hg-git

and it reports exception from client.py:1633:_http_request() - NotGotRepository()

client try GET request for url 
`str: https://git.code.sf.net/p/ion-dtn/open-source%20ion-dtn-open-source/info/refs?service=git-upload-pack`

server reports 404 on that one.

what goes wrong?

**Comment by jelmer** [comment]
Can you reproduce this with pure Dulwich, i.e. 'dulwich clone'?

**Comment by alexrayne** [comment]
how?

**Comment by alexrayne** [comment]
hg-git invokes dulwich client at `fetch_pack` with path arg: `b'https://git.code.sf.net/p/ion-dtn/open-source%20ion-dtn-open-source'`

that has call _http_request for url `https://git.code.sf.net/p/ion-dtn/open-source%20ion-dtn-open-source/info/refs?service=git-upload-pack`
after that exception reported.

same dulwich  look in github repo well

**Comment by jelmer** [comment]
C Git works with this URL: https://git.code.sf.net/p/ion-dtn/open-source:

```
% git clone https://git.code.sf.net/p/ion-dtn/open-source ion-dtn-open-source
Cloning into 'ion-dtn-open-source'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 7 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (7/7), 576 bytes | 576.00 KiB/s, done.
```

And so does Dulwich:

```
% dulwich clone https://git.code.sf.net/p/ion-dtn/open-source ion-dtn-open-source1
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Compressing objects: 100% (5/5), done.
Total 7 (delta 0), reused 0 (delta 0)
Checking out 23960fa1ba518dda9adc2c68ad28fc22b107cfda
```

hg-git is passing in an incorrect URL here.

**Comment by alexrayne** [comment]
thanks
