### ISSUE TITLE
tagging

### ISSUE THREAD

**Issue by kloczek** [dulwich/dulwich#899]
To be honest I'm confused a bit abou git tafgging pattern :/
After `0.10.24` is now `dulwich-0.10.25`.
Is it any difference betweek `<version>` and `dulwich-<version>`?

**Comment by jelmer** [comment]
0.20.24 was missing the prefix (every other release has dulwich-). I've just created a dulwich-0.20.24 tag. Sorry for the confusion.

**Comment by kloczek** [comment]
Please consider change tagging convention if that convention is not used by some automation.
Reason for that is that tag as `<verion.with,dots>` is that tag is marking release so repeating that i tag is a bit pointless.
Second reason is that autogenerated by github/gitlab has as base directory name `repo_name>-<tag>/` 
Just checked on my 3.5k spec files:
```console
[tkloczko@barrel SPECS]$ grep Source0:.*VCS * -h|wc -l; grep Source0:.*VCS * -h|sort| uniq -c | sort -n| tail -5
1158
     17 Source0:        %{VCS}/releases/download/%{version}/%{name}-%{version}.tar.gz
     22 Source0:        %{VCS}/-/archive/%{version}/%{name}-%{version}.tar.bz2
     27 Source0:        %{VCS}/archive/%{name}-%{version}.tar.gz
    398 Source0:        %{VCS}/archive/v%{version}/%{name}-%{version}.tar.gz
    416 Source0:        %{VCS}/archive/%{version}/%{name}-%{version}.tar.gz
```
github automatically skips first character before numbers so even if tag is `v<version>` github autogenetated tar ball has base directory `<repo_name>-<version>/`.
I want only to say that using tag like 'release-<version>` is not the most common convention and makes packaging a bit more complicated.

**Comment by jelmer** [comment]
On Mon, Aug 23, 2021 at 02:25:29PM -0700, Tomasz Kłoczko wrote:
> Please consider change tagging convention if that convention is not used by some automation.
> Reason for that is that tag as `<verion.with,dots>` is that tag is marking release so repeating that i tag is a bit pointless.
> Second reason is that autogenerated by github/gitlab has as base directory name `repo_name>-<tag>/` 
> Just checked on my 3.5k spec files:
> ```console
> ***@***.*** SPECS]$ grep Source0:.*VCS * -h|wc -l; grep Source0:.*VCS * -h|sort| uniq -c | sort -n| tail -5
> 1158
>      17 Source0:        %{VCS}/releases/download/%{version}/%{name}-%{version}.tar.gz
>      22 Source0:        %{VCS}/-/archive/%{version}/%{name}-%{version}.tar.bz2
>      27 Source0:        %{VCS}/archive/%{name}-%{version}.tar.gz
>     398 Source0:        %{VCS}/archive/v%{version}/%{name}-%{version}.tar.gz
>     416 Source0:        %{VCS}/archive/%{version}/%{name}-%{version}.tar.gz
> ```
> github automatically skips first character before numbers so even if tag is `v<version>` github autogenetated tar ball has base directory `<repo_name>-<version>/`.
> I want only to say that using tag like 'release-<version>` is not the most common convention and makes packaging a bit more complicated.

The canonical tarballs can be found on pypi rather than GitHub, and I
believe the directory name there is as you would expect.

Prefixing tags with the project name can sometimes be helpful when
there are multiple project names in a repository with possibly
conflicting version numbers, which is why I use to that convention.

Cheers,

Jelmer

-- 
Jelmer Vernooĳ ***@***.***>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by kloczek** [comment]
I reason to prefer to use VCS tar balls because with those tar balls it it 100% guarantee that git patches added after tag will be applying without rejections.
That is only reason why I'm using VCS tar balls so often.
We are living in the world where all software with which we can deal is not-so-enough-tested-software(tm). From that point of view using VCS archives allows apply any patches with lowest possible overhead on packaging layer.
