### ISSUE TITLE
Intentional use of mutable default arguments?

### ISSUE THREAD

**Issue by laprej** [dulwich/dulwich#912]
https://github.com/dulwich/dulwich/blob/d4ed520b292fdb9ba0513324315517274ac31537/dulwich/object_store.py#L334-L335

These sets will retain their values across multiple calls.  Was this the intended behavior?  If so it probably warrants a comment?

https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments

**Comment by jelmer** [comment]
Where are the arguments mutated?
