### ISSUE TITLE
How to checkout or clone branch?

### ISSUE THREAD

**Issue by alchem1ster** [dulwich/dulwich#915]
Can someone answer a couple of questions, I would be extremely grateful:
1. Let's say that we want to clone some repository from github that have two branches: `main` and `dev`, but porcelain.clone() always gets an active main HEAD. How do I download a particular other branch directly (for example, `dev`)?
2. If we have already cloned this repository to local folder, how to change all files (git checkout?) from `main` to `dev` branch and move HEAD to latest commit in `dev` branch?

**Comment by jelmer** [comment]
In general, please use stackoverflow or the mailing list for questions, rather than the bugtracker.

To answer your question, this is not currently supported. Pull request #851 implements it. It's pretty much ready to merge, I just haven't had time to do so.

**Comment by alchem1ster** [comment]
> In general, please use stackoverflow or the mailing list for questions, rather than the bugtracker.

I asked this question on stackoverflow, but didn't get an any answer for 20 hours. Also, I noticed the Question label in the issues section of this repository and thought I'd ask the question here. Sorry :)
