### ISSUE TITLE
Gecos is None

### ISSUE THREAD

**Issue by hardyvince** [dulwich/dulwich#917]
in repo.py we can run on error if pwd for full name gives back none. Simple solution is a check like
--- a/dulwich/repo.py                         
+++ b/dulwich/repo.py                         
@@ -146,7 +146,8 @@ def _get_default_identity() -> Tuple[str, str]: 
        except KeyError:                                  
            fullname = None                           
        else:
\-            fullname = gecos.split(",")[0]   
\+            if not gecos:                    
\+                fullname = gecos.split(",")[0]                                                  
   if not fullname:                                  
        fullname = username                       
email = os.environ.get("EMAIL")

**Comment by jelmer** [comment]
That seems sensible - care to submit a PR?

**Comment by hardyvince** [comment]
created> https://github.com/dulwich/dulwich/pull/918

**Comment by jelmer** [comment]
Fixed in master.
