### ISSUE TITLE
non-closed .idx and .pack files when using porcelain.clone

### ISSUE THREAD

**Issue by speter18** [dulwich/dulwich#922]
When calling
```
porcelain.clone(remote_repo, local_path, password=XXX, username=XXX)
```
it turns out that the `XXX.pack` and `XXX.idx` files in `.git/objects/pack` folder are not closed, which can lead to strange "no access" errors when trying to e.g. manually remove those files lateron.

When debugging, it seems that there is returned a `Repo` object by `clone()`, which is containing those filehandles. This means that a workaround to solve this issue is to call
```
r = porcelain.clone(remote_repo, local_path, password=XXX, username=XXX)
r.close()
```

System parameters:
Windows 10
Python 3.7
dulwich 0.20.24

**Comment by jelmer** [comment]
This is intentional - the repository is kept open for performance reasons; if you want to use it after cloning, it won't have to re-read all indexes. 

We could possibly close() it if this is too surprising; users that care about the performance could just call GitClient.clone() directly.

**Comment by speter18** [comment]
If the close command is required after calling clone, that would be fine, but I think it should be properly communicated in the docs.
