### ISSUE TITLE
IgnoreFilterManager.is_ignored does not handle escaped `[]` in file names correctly

### ISSUE THREAD

**Issue by achimgaedke** [dulwich/dulwich#930]
To reproduce:

```
mkdir test
cd test
git init
```

create a `.gitignore` file with the contents:

```
/foo\[bar\]
/foo
```

Create a file `foo[bar]` with `touch "foo[bar]"` and use `git status` to confirm that `foo[bar]` is ignored (i.e. not listed).

Then start python with dulwich:
```
ifm = IgnoreFilterManager.from_repo(Repo("."))
print(ifm.is_ignored("foo"))
print(ifm.is_ignored("foo[bar]"))
```

results in:
```
True
None
```

The `None` is unexpected as git ignores `foo[bar]`.
I would expect the same return value for `foo[bar]` as for `foo`, i.e. `True`.

Versions:
* Ubuntu Linux 20.04
* git 2.25.1
* python 3.9.9
* dulwich 0.20.32

This is a follow-up issue from https://github.com/iterative/dvc/issues/7274

**Comment by dtrifiro** [comment]
Should be fixed in https://github.com/jelmer/dulwich/commit/e7818a9482f055415eeb2bd9fa1d51f5329424f9, waiting for a new dulwich release
